# download path contains version without the last (fourth) digit
%define libo_version 5.2.0
# Should contain .alphaX / .betaX, if this is pre-release (actually
# pre-RC) version. The pre-release string is part of tarball file names,
# so we need a way to define it easily at one place.
%define libo_prerelease %{nil}
# Should contain any suffix of release tarball name, e.g., -buildfix1.
%define libo_buildfix %{nil}
# rhbz#715152 state vendor
%if 0%{?rhel}
%define vendoroption --with-vendor="Red Hat, Inc."
%define libo_use_python3 %{nil}
%define libo_python python
%define libo_python_sitearch %{python_sitearch}
%endif
%if 0%{?fedora}
%define libo_use_python3 1
%define libo_python python3
%define libo_python_sitearch %{python3_sitearch}
%define vendoroption --with-vendor="The Fedora Project"
%endif
# rhbz#465664 jar-repacking breaks help by reordering META-INF/MANIFEST.MF
%define __jar_repack %{nil}
# make it easier to download sources from pre-release site
# http://dev-builds.libreoffice.org/pre-releases/src
%define source_url http://dev-builds.libreoffice.org/pre-releases/src
# %%define source_url http://download.documentfoundation.org/libreoffice/src/%{libo_version}
# URL for external projects' tarballs
%define external_url http://dev-www.libreoffice.org/src/
%if 0%{?fedora}
%global weak_deps 1
%global file_triggers 1
%endif
%global girapiversion 0.1

# remove workdir at the end of %%build, to allow build on space-constrained machines
%ifarch s390 s390x
%bcond_without smallbuild
%else
%bcond_with smallbuild
%endif

# generated by %%langpack definitions
%global langpack_langs %{nil}

%global bundling_options %{nil}

Summary:        Free Software Productivity Suite
Name:           libreoffice
Epoch:          1
Version:        %{libo_version}.4
Release:           1000.HDZ
License:        (MPLv1.1 or LGPLv3+) and LGPLv3 and LGPLv2+ and BSD and (MPLv1.1 or GPLv2 or LGPLv2 or Netscape) and Public Domain and ASL 2.0 and Artistic and MPLv2.0 and CC0
URL:            http://www.libreoffice.org/

Source0:        %{source_url}/libreoffice-%{version}%{?libo_prerelease}%{?libo_buildfix}.tar.xz
Source1:        %{source_url}/libreoffice-help-%{version}%{?libo_prerelease}%{?libo_buildfix}.tar.xz
Source2:        %{source_url}/libreoffice-translations-%{version}%{?libo_prerelease}%{?libo_buildfix}.tar.xz
Source3:        http://dev-www.libreoffice.org/extern/185d60944ea767075d27247c3162b3bc-unowinreg.dll
Source4:        libreoffice-multiliblauncher.sh
Source5:        %{external_url}/a7983f859eafb2677d7ff386a023bc40-xsltml_2.1.2.zip
Source6:        %{external_url}/ce12af00283eb90d9281956524250d6e-xmlsec1-1.2.20.tar.gz
Source7:        %{external_url}/798b2ffdc8bcfe7bca2cf92b62caf685-rhino1_5R5.zip
Source8:        %{external_url}/35c94d2df8893241173de1d16b6034c0-swingExSrc.zip
#Unfortunately later versions of hsqldb changed the file format, so if we use a later version we loose
#backwards compatability.
Source9:        %{external_url}/17410483b5b5f267aa18b7e00b65e6e0-hsqldb_1_8_0.zip
%global bundling_options %{?bundling_options} --without-system-hsqldb

%if 0%{?fedora}
Source40:       %{external_url}/4b87018f7fff1d054939d19920b751a0-collada2gltf-master-cb1d97788a.tar.bz2
%endif

# symbolic icons
Source42:       https://raw.githubusercontent.com/gnome-design-team/gnome-icons/master/apps-symbolic/Adwaita/scalable/apps/libreoffice-base-symbolic.svg
Source43:       https://raw.githubusercontent.com/gnome-design-team/gnome-icons/master/apps-symbolic/Adwaita/scalable/apps/libreoffice-calc-symbolic.svg
Source44:       https://raw.githubusercontent.com/gnome-design-team/gnome-icons/master/apps-symbolic/Adwaita/scalable/apps/libreoffice-draw-symbolic.svg
Source45:       https://raw.githubusercontent.com/gnome-design-team/gnome-icons/master/apps-symbolic/Adwaita/scalable/apps/libreoffice-impress-symbolic.svg
Source46:       https://raw.githubusercontent.com/gnome-design-team/gnome-icons/master/apps-symbolic/Adwaita/scalable/apps/libreoffice-main-symbolic.svg
Source47:       https://raw.githubusercontent.com/gnome-design-team/gnome-icons/master/apps-symbolic/Adwaita/scalable/apps/libreoffice-math-symbolic.svg
Source48:       https://raw.githubusercontent.com/gnome-design-team/gnome-icons/master/apps-symbolic/Adwaita/scalable/apps/libreoffice-writer-symbolic.svg

%if 0%{?rhel}
%global bundling_options %{?bundling_options} --with-system-ucpp --with-system-orcus --with-system-mdds --with-system-libcmis --with-system-libwps --with-system-libpagemaker
%endif

# build tools
BuildRequires: autoconf
BuildRequires: automake
BuildRequires: bc
BuildRequires: binutils
BuildRequires: bison
BuildRequires: desktop-file-utils
BuildRequires: doxygen
BuildRequires: findutils
BuildRequires: flex
BuildRequires: gcc-c++
BuildRequires: gdb
BuildRequires: git
BuildRequires: gperf
BuildRequires: icu
BuildRequires: make
BuildRequires: perl(Archive::Zip)
BuildRequires: perl(Digest::MD5)
BuildRequires: ucpp
%if 0%{?fedora}
BuildRequires: libappstream-glib
%endif
BuildRequires: zip

# libs / headers - common
BuildRequires: %{libo_python}-devel
BuildRequires: boost-devel
BuildRequires: cups-devel
BuildRequires: expat-devel
BuildRequires: fontpackages-devel
BuildRequires: glm-devel
BuildRequires: hyphen-devel
BuildRequires: libicu-devel
BuildRequires: libjpeg-turbo-devel
BuildRequires: lpsolve-devel
BuildRequires: openldap-devel
BuildRequires: pam-devel
BuildRequires: pkgconfig(bluez)
BuildRequires: pkgconfig(cppunit)
BuildRequires: pkgconfig(dbus-glib-1)
BuildRequires: pkgconfig(evolution-data-server-1.2)
BuildRequires: pkgconfig(freetype2)
BuildRequires: pkgconfig(glew) >= 1.10.0
BuildRequires: pkgconfig(glu)
BuildRequires: pkgconfig(graphite2)
BuildRequires: pkgconfig(gstreamer-1.0)
BuildRequires: pkgconfig(gstreamer-plugins-base-1.0)
BuildRequires: pkgconfig(gtk+-2.0)
BuildRequires: pkgconfig(harfbuzz)
BuildRequires: pkgconfig(hunspell)
BuildRequires: pkgconfig(ice)
BuildRequires: pkgconfig(lcms2)
BuildRequires: pkgconfig(libabw-0.1)
BuildRequires: pkgconfig(libcdr-0.1)
BuildRequires: pkgconfig(libclucene-core)
BuildRequires: pkgconfig(libcurl)
BuildRequires: pkgconfig(libetonyek-0.1)
BuildRequires: pkgconfig(libexttextcat)
BuildRequires: pkgconfig(libfreehand-0.1)
BuildRequires: pkgconfig(libidn)
BuildRequires: pkgconfig(liblangtag)
BuildRequires: pkgconfig(libmspub-0.1)
BuildRequires: pkgconfig(libmwaw-0.3)
BuildRequires: pkgconfig(libodfgen-0.1)
BuildRequires: pkgconfig(librevenge-0.0)
BuildRequires: pkgconfig(libvisio-0.1)
BuildRequires: pkgconfig(libwpd-0.10)
BuildRequires: pkgconfig(libwpg-0.3)
BuildRequires: pkgconfig(libxml-2.0)
BuildRequires: pkgconfig(libxslt)
BuildRequires: pkgconfig(mythes)
BuildRequires: pkgconfig(neon)
BuildRequires: pkgconfig(nss)
BuildRequires: pkgconfig(poppler)
BuildRequires: pkgconfig(poppler-cpp)
BuildRequires: pkgconfig(redland)
BuildRequires: pkgconfig(sane-backends)
BuildRequires: pkgconfig(xext)
BuildRequires: pkgconfig(xinerama)
BuildRequires: pkgconfig(xt)
BuildRequires: pkgconfig(zlib)
BuildRequires: postgresql-devel
BuildRequires: unixODBC-devel
BuildRequires: vigra-devel
BuildRequires: pkgconfig(libe-book-0.1)
BuildRequires: pkgconfig(mdds-1.2)
BuildRequires: pkgconfig(liborcus-0.11)
BuildRequires: pkgconfig(libcmis-0.5)
BuildRequires: pkgconfig(libwps-0.4)
BuildRequires: pkgconfig(libpagemaker-0.0)

# libs / headers - conditional
%if 0%{?fedora}
BuildRequires: firebird-devel
BuildRequires: kdelibs4-devel
BuildRequires: openCOLLADA-devel
BuildRequires: pkgconfig(gobject-introspection-1.0)
BuildRequires: pkgconfig(gtk+-3.0)
BuildRequires: pkgconfig(libeot)
BuildRequires: pkgconfig(libgltf-0.0)
%endif

# java stuff
BuildRequires: ant
BuildRequires: bsh
BuildRequires: java-devel
BuildRequires: junit
BuildRequires: pentaho-reporting-flow-engine

# fonts needed for unit tests
BuildRequires: liberation-mono-fonts
BuildRequires: liberation-sans-fonts
BuildRequires: liberation-serif-fonts

Requires: %{name}-writer%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-calc%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-impress%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-draw%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-math%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-base%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-emailmerge%{?_isa} = %{epoch}:%{version}-%{release}

# not upstreamed
Patch0:  openoffice.org-2.4.0.ooo86080.unopkg.bodge.patch
# not upstreamed
Patch1:  openoffice.org-3.1.0.oooXXXXX.solenv.allowmissing.patch
# not upstreamed
Patch2:  libreoffice-installfix.patch
# not upstreamed
Patch3: 0001-Resolves-rhbz-1035092-no-shortcut-key-for-Italian-To.patch
# not upstreamed
Patch4: 0001-disable-firebird-unit-test.patch
# not upstreamed
Patch5: 0001-never-run-autogen.sh.patch
# not upstreamed
Patch6: 0001-add-X-TryExec-entries-to-desktop-files.patch
Patch7: 0001-Resolves-rhbz-1326304-cannot-detect-loss-of-wayland-.patch
Patch8: 0001-don-t-autocapitalize-words-that-follow-a-field-mark.patch
Patch9: 0001-a11y-crash-on-deleting-certain-frame-in-certain-docu.patch
Patch10: 0001-Resolves-rhbz-1353069-don-t-clear-XATTR_FILL-from-st.patch
Patch11: 0001-Resolves-rhbz-1351224-wayland-grab-related-crashes.patch
Patch12: 0001-Resolves-rhbz-1352965-gtk3-infinite-clipboard-recurs.patch
Patch13: 0001-rhbz-1351292-correctly-set-edit-mode.patch
Patch14: 0001-Related-rhbz-1351369-gtk3-clipboards-have-to-live-to.patch
Patch15: 0001-Related-rhbz-1065807-recover-using-xdg-templates-and.patch
Patch16: 0001-curl-7.50.0-has-CURL-as-typedef-struct-Curl_easy.patch



%define instdir %{_libdir}
%define baseinstdir %{instdir}/libreoffice
%define sdkinstdir %{baseinstdir}/sdk
%define datadir %{_datadir}/%{name}
%define fontname opensymbol

# rhbz#1085420 make sure we do not provide bundled libraries
%if 0%{?rhel}
%global libo_bundled_libs_filter ^liborcus(-parser)?-0\\.11\\.so.*$
%global __provides_exclude %{libo_bundled_libs_filter}
%global __requires_exclude %{libo_bundled_libs_filter}
%endif

%description
LibreOffice is an Open Source, community-developed, office productivity suite.
It includes the key desktop applications, such as a word processor,
spreadsheet, presentation manager, formula editor and drawing program, with a
user interface and feature set similar to other office suites.  Sophisticated
and flexible, LibreOffice also works transparently with a variety of file
formats, including Microsoft Office File Formats.

%package filters
Summary: All import / export filters
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-calc%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-draw%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-graphicfilter%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-impress%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-math%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-writer%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-xsltfilter%{?_isa} = %{epoch}:%{version}-%{release}

%description filters
Metapackage to pull in all subpackages that contain import or export
filters.

%package core
Summary: Core modules for LibreOffice
Requires: %{name}-%{fontname}-fonts = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-data = %{epoch}:%{version}-%{release}
%if 0%{?fedora}
Requires: %{name}-gtk3%{?_isa} = %{epoch}:%{version}-%{release}
%else
# these two plugins used to be part of core--keep it that way
Requires: %{name}-gtk2%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-x11%{?_isa} = %{epoch}:%{version}-%{release}
%endif
Requires: liberation-sans-fonts, liberation-serif-fonts, liberation-mono-fonts
Requires: dejavu-sans-fonts, dejavu-serif-fonts, dejavu-sans-mono-fonts
Requires: google-crosextra-caladea-fonts, google-crosextra-carlito-fonts
Requires: %{name}-langpack-en = %{epoch}:%{version}-%{release}
# rhbz#949106 libreoffice-core drags in both openjdk 1.7.0 and 1.8.0
Requires: java-headless >= 1:1.6
Obsoletes: libreoffice-appdata < 1:4.3.3.0
Obsoletes: libreoffice-binfilter < 1:4.0.0.0
Obsoletes: libreoffice-headless < 1:4.4.0.0
Obsoletes: libreoffice-javafilter < 1:4.1.0.0
Obsoletes: openoffice.org-core < 1:3.3.1
Obsoletes: openoffice.org-brand < 1:3.3.1, broffice.org-brand < 1:3.3.1
Obsoletes: openoffice.org-headless < 1:3.3.1
Obsoletes: openoffice.org-javafilter < 1:3.3.1
Obsoletes: openoffice.org-langpack-ms < 1:3.3.1, libreoffice-langpack-ms < 1:3.3.99.1
Obsoletes: openoffice.org-langpack-ur < 1:3.3.1, libreoffice-langpack-ur < 1:3.3.99.1
Obsoletes: openoffice.org-testtools < 1:3.3.1
Obsoletes: libreoffice-testtools < 1:3.4.99.1
Obsoletes: autocorr-eu < 1:4.0.1.2
Provides: libreoffice-appdata = %{epoch}:%{version}-%{release}
Provides: libreoffice-appdata%{?_isa} = %{epoch}:%{version}-%{release}
Provides: libreoffice-headless = %{epoch}:%{version}-%{release}
Provides: libreoffice-headless%{?_isa} = %{epoch}:%{version}-%{release}

%description core
The shared core libraries and support files for LibreOffice.

%package pyuno
Summary: Python support for LibreOffice
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{libo_python}%{?_isa}
Obsoletes: openoffice.org-pyuno < 1:3.3.1

%description pyuno
Python bindings for the LibreOffice UNO component model. Allows scripts both
external to LibreOffice and within the internal LibreOffice scripting framework
to be written in python.

%package base
Summary: Database front-end for LibreOffice
Requires: pentaho-reporting-flow-engine
Requires: postgresql-jdbc
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-calc%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-data = %{epoch}:%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: %{name}-report-builder < 1:4.1.0.0
Obsoletes: openoffice.org-base-core < 1:3.3.1
Obsoletes: openoffice.org-base < 1:3.3.1, broffice.org-base < 1:3.3.1
Obsoletes: openoffice.org-report-builder < 1:3.3.1

%description base
GUI database front-end for LibreOffice. Allows creation and management of 
databases through a GUI.

%package bsh
Summary: BeanShell support for LibreOffice
Requires: bsh
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-bsh < 1:3.3.1

%description bsh
Support BeanShell scripts in LibreOffice.

%package officebean
Summary: JavaBean for LibreOffice Components
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}

%description officebean
Allows embedding of LibreOffice documents within the Java environment. It
provides a Java AWT window into which the backend LibreOffice process draws
its visual representation

%package rhino
Summary: JavaScript support for LibreOffice
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-rhino < 1:3.3.1

%description rhino
Support JavaScript scripts in LibreOffice.

%package wiki-publisher
Summary: Create Wiki articles on MediaWiki servers with LibreOffice
Requires: %{name}-writer%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-wiki-publisher < 1:3.3.1

%description wiki-publisher
The Wiki Publisher enables you to create Wiki articles on MediaWiki servers
without having to know the syntax of the MediaWiki markup language. Publish
your new and existing documents transparently with writer to a wiki page.

%package nlpsolver
Summary: Non-linear solver engine for LibreOffice Calc
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-calc%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}

%description nlpsolver
A non-linear solver engine for Calc as an alternative to the default linear
programming model when more complex, nonlinear programming is required.

%package ogltrans
Summary: 3D OpenGL slide transitions for LibreOffice
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-impress%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-ogltrans < 1:3.3.1

%description ogltrans
OpenGL Transitions enable 3D slide transitions to be used in LibreOffice.
Requires good quality 3D support for your graphics card for best experience.

%package pdfimport
Summary: PDF Importer for LibreOffice Draw
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-draw%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-pdfimport < 1:3.3.1

%description pdfimport
The PDF Importer imports PDF into drawing documents to preserve layout
and enable basic editing of PDF documents.

%package %{fontname}-fonts
Summary: LibreOffice dingbats font
Requires: fontpackages-filesystem
Obsoletes: openoffice.org-fonts < 1:3.3.1
Obsoletes: openoffice.org-opensymbol-fonts < 1:3.3.1
BuildArch: noarch

%description %{fontname}-fonts
A dingbats font, OpenSymbol, suitable for use by LibreOffice for bullets and
mathematical symbols. 

%package writer
Summary: LibreOffice Word Processor Application
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-data = %{epoch}:%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-writer-core < 1:3.3.1
Obsoletes: openoffice.org-writer < 1:3.3.1, broffice.org-writer < 1:3.3.1

%description writer
The LibreOffice Word Processor application.

%package emailmerge
Summary: Email mail-merge component for LibreOffice 
Requires: %{name}-writer%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-emailmerge < 1:3.3.1

%description emailmerge
Enables the LibreOffice writer module to mail-merge to email.

%package calc
Summary: LibreOffice Spreadsheet Application
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-data = %{epoch}:%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-calc-core < 1:3.3.1
Obsoletes: openoffice.org-calc < 1:3.3.1, broffice.org-calc < 1:3.3.1

%description calc
The LibreOffice Spreadsheet application.

%package draw
Summary: LibreOffice Drawing Application
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-data = %{epoch}:%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-pdfimport%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-graphicfilter%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-draw-core < 1:3.3.1
Obsoletes: openoffice.org-draw < 1:3.3.1, broffice.org-draw < 1:3.3.1

%description draw
The LibreOffice Drawing Application.

%package impress
Summary: LibreOffice Presentation Application
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-data = %{epoch}:%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
%if 0%{?weak_deps}
Recommends: %{name}-ogltrans%{?_isa} = %{epoch}:%{version}-%{release}
%endif
Obsoletes: %{name}-presentation-minimizer < 2:4.2.0.0-1.alpha1
Obsoletes: %{name}-presenter-screen < 2:4.0.0.0-1.beta1
Obsoletes: openoffice.org-impress-core < 1:3.3.1
Obsoletes: openoffice.org-impress < 1:3.3.1, broffice.org-impress < 1:3.3.1
Obsoletes: openoffice.org-presentation-minimizer < 1:3.3.1
Obsoletes: openoffice.org-presenter-screen < 1:3.3.1
Provides: %{name}-presentation-minimizer = %{epoch}:%{version}-%{release}
Provides: %{name}-presentation-minimizer%{?_isa} = %{epoch}:%{version}-%{release}
Provides: %{name}-presenter-screen = %{epoch}:%{version}-%{release}
Provides: %{name}-presenter-screen%{?_isa} = %{epoch}:%{version}-%{release}

%description impress
The LibreOffice Presentation Application.

%package math
Summary: LibreOffice Equation Editor Application
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-math-core < 1:3.3.1
Obsoletes: openoffice.org-math < 1:3.3.1, broffice.org-math < 1:3.3.1

%description math 
The LibreOffice Equation Editor Application.

%package graphicfilter
Summary: LibreOffice Extra Graphic filters
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-data = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-graphicfilter < 1:3.3.1

%description graphicfilter
The graphicfilter module for LibreOffice provides graphic filters, e.g. svg and
flash filters.

%package xsltfilter
Summary: Optional xsltfilter module for LibreOffice
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: openoffice.org-xsltfilter < 1:3.3.1

%description xsltfilter
The xsltfilter module for LibreOffice, provides additional docbook and
xhtml export transforms. Install this to enable docbook export.

%package postgresql
Summary: PostgreSQL connector for LibreOffice
Requires: %{name}-base%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Requires: postgresql-libs%{?_isa}

%description postgresql
A PostgreSQL connector for the database front-end for LibreOffice. Allows
creation and management of PostgreSQL databases through a GUI.

%package ure
Summary: UNO Runtime Environment
#rhbz#1164551 we want to ensure that a libjvm.so of this arch is available
%if 0%{?__isa_bits} == 64
%global mark64 ()(64bit)
%endif
Requires: unzip%{?_isa}, libjvm.so%{?mark64}
Obsoletes: openoffice.org-ure < 1:3.3.1

%description ure
UNO is the component model of LibreOffice. UNO offers interoperability between
programming languages, other components models and hardware architectures,
either in process or over process boundaries, in the Intranet as well as in the
Internet. UNO components may be implemented in and accessed from any
programming language for which a UNO implementation (AKA language binding) and
an appropriate bridge or adapter exists

%package sdk
Summary: Software Development Kit for LibreOffice
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}
Requires: unzip%{?_isa}, java-devel
Obsoletes: openoffice.org-sdk < 1:3.3.1, openoffice.org-devel < 1:3.3.1

%description sdk
The LibreOffice SDK is an add-on for the LibreOffice office suite. It provides
the necessary tools for programming using the LibreOffice APIs and for creating
extensions (UNO components) for LibreOffice.  To set the build environment for
building against the sdk use %{sdkinstdir}/setsdkenv_unix.sh.

%package sdk-doc
Summary: Software Development Kit documentation for LibreOffice
Obsoletes: openoffice.org-sdk-doc < 1:3.3.1

%description sdk-doc
This provides documentation for programming using the LibreOffice APIs
and examples of creating extensions (UNO components) for LibreOffice.

%package glade
Summary: Support for creating LibreOffice dialogs in glade
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-ure%{?_isa} = %{epoch}:%{version}-%{release}

%description glade
%{name}-glade contains a catalog of LibreOffice-specific widgets for
glade and ui-previewer tool to check the visual appearance of dialogs.

%package librelogo
Summary: LibreLogo scripting language
Requires: %{name}-writer%{?_isa} = %{epoch}:%{version}-%{release}
Requires: %{name}-pyuno%{?_isa} = %{epoch}:%{version}-%{release}

%description librelogo
Enables LibreLogo scripting in Writer. LibreLogo is a Logo-like
programming language with interactive vectorgraphics for education and
DTP.

%package data
Summary: LibreOffice data files
BuildArch: noarch

%description data
%{name}-data contains platform-independent data files.

%package x11
Summary: LibreOffice generic X11 support plug-in
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Provides: %{name}-plugin = %{epoch}:%{version}-%{release}
Provides: %{name}-plugin%{?_isa} = %{epoch}:%{version}-%{release}
%if 0%{?weak_deps}
Supplements: (%{name}-core%{?_isa} and Xserver)
%endif

%description x11
A plug-in for LibreOffice that enables generic X11 support.

%package gtk2
Summary: LibreOffice GTK+ 2 integration plug-in
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Provides: %{name}-plugin = %{epoch}:%{version}-%{release}
Provides: %{name}-plugin%{?_isa} = %{epoch}:%{version}-%{release}
%if 0%{?weak_deps}
Supplements: (%{name}-core%{?_isa} and gtk2%{?_isa})
%endif

%description gtk2
A plug-in for LibreOffice that enables integration into GTK+ 2 environment.

%if 0%{?fedora}

%package kde4
Summary: LibreOffice KDE integration plug-in
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Obsoletes: %{name}-kde < 1:5.1.1.3-2
Provides: %{name}-kde = %{epoch}:%{version}-%{release}
Provides: %{name}-kde%{?_isa} = %{epoch}:%{version}-%{release}
Provides: %{name}-plugin = %{epoch}:%{version}-%{release}
Provides: %{name}-plugin%{?_isa} = %{epoch}:%{version}-%{release}

%description kde4
A plug-in for LibreOffice that enables integration into the KDE desktop environment.

%package gtk3
Summary: LibreOffice GTK+ 3 integration plug-in
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
Supplements: (%{name}-core%{?_isa} and gtk3%{?_isa})

%description gtk3
A plug-in for LibreOffice that enables integration into GTK+ 3 environment.

%package -n libreofficekit
Summary: A library providing access to LibreOffice functionality
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release}
License: MPLv2.0

%description -n libreofficekit
LibreOfficeKit can be used to access LibreOffice functionality
through C/C++, without any need to use UNO.

For now it only offers document conversion (in addition to an
experimental tiled rendering API).

%package -n libreofficekit-devel
Summary: Development files for libreofficekit
Requires: libreofficekit%{?_isa} = %{epoch}:%{version}-%{release}
License: MPLv2.0

%description -n libreofficekit-devel
The libreofficekit-devel package contains libraries and header files for
developing applications that use libreofficekit.

%endif

%if 0%{?_enable_debug_packages}

%package gdb-debug-support
Summary: Additional support for debugging with gdb
Requires: gdb%{?_isa}
Requires: %{libo_python}-six
Requires: libreoffice-core%{?_isa} = %{epoch}:%{version}-%{release}
%if 0%{?weak_deps}
Supplements: libreoffice-debuginfo%{?_isa} = %{epoch}:%{version}-%{release}
%endif

%description gdb-debug-support
This package provides gdb pretty printers for package %{name}.

%files gdb-debug-support
%{_datadir}/gdb/auto-load%{baseinstdir}
%{_datadir}/libreoffice/gdb

%endif

%define _langpack_common() \
%{baseinstdir}/program/resource/*%{1}.res  \
%{baseinstdir}/share/config/soffice.cfg/modules/*/ui/res/%{1}.zip \
%{baseinstdir}/share/config/soffice.cfg/*/ui/res/%{1}.zip \
%{baseinstdir}/share/template/%{1} \
%{baseinstdir}/share/registry/Langpack-%{1}.xcd \
%{baseinstdir}/share/registry/res/registry_%{1}.xcd \
%{baseinstdir}/share/registry/res/fcfg_langpack_%{1}.xcd \
%{nil}

# Defines a language pack subpackage.
#
# It's necessary to define language code (-l) and language name (-n).
# Additionally, it's possible
# * to require autocorr, hunspell, hyphen or mythes package or font for
#   given language,
# * to obsolete openoffice.org-langpack package,
# * to provide libreoffice-langpack-loc package, where loc is glibc
#   locale--this is necessary for yum to pick it automatically,
# * to require other, unrelated, packages,
# * to specify file serving as file list.
# For these, lower case character argument takes an argument specifying
# language, upper case character argument uses language from -l.
#
# All remaining arguments are considered to be files and added to the file
# list.
#
# Aa:  autocorr dependency
# c:   additional config file (just the name stem)
# E    the package does not contain any files (i.e., has empty filelist)
# Ff:  font language dependency
# Hh:  hunspell dependency
# i:   additional language added to this package
# L:   internal (LibreOffice) language code, used in file names
# l:   language code, e.g., cs
# Mm:  mythes dependency
# n:   language name, e.g., Czech
# Oo:  Obsoletes: of openoffice.org-langpack
# Vv:  Very archaic Obsoletes: of openoffice.org-langpack
# Ww:  Archaic Obsoletes: of openoffice.org2-langpack
# p:   Provides: of libreoffice-langpack
# r:   comma-separated list of additional requires
# S:s: script classification (cjk, ctl). -S is only a marker, as it does
#      not add any .xcd into the package (the file does not exist for at
#      least one CTL-using locale, si)
# T    has help files
# Xx:  has autotext definitions
# Yy:  hyphen dependency
#
# Example:
# libreoffice-langpack-cs: langpack for Czech lang. requiring hyphen-cs,
# autocorr-cs, mythes-cs-CZ and suitable font, obsoleting
# openoffice.org-langpack-cs_CZ:
# %%langpack -l cs -n Czech -H -A -m cs-CZ
#  b de g  jk     q  tu    z BCD  G IJK  N PQR  U    Z0123456789
%define langpack(Aa:c:EFf:Hh:i:L:l:Mm:n:p:Oo:r:S:s:TVv:Ww:Xx:Yy:) \
%define lang %{-l:%{-l*}}%{!-l:%{error:Language code not defined}} \
%define _langpack_lang %{-L:%{-L*}}%{!-L:%{lang}} \
%define pkgname langpack-%{lang} \
%define langname %{-n:%{-n*}}%{!-n:%{error:Language name not defined}} \
\
%global langpack_langs %{langpack_langs} %{_langpack_lang} %{-i:%{-i*}} \
\
%package %{pkgname} \
Summary: %{langname} language pack for LibreOffice \
Requires: %{name}-core%{?_isa} = %{epoch}:%{version}-%{release} \
%{-a:Requires: autocorr-%{-a*}}%{!-a:%{-A:Requires: autocorr-%{lang}}} \
%{-f:Requires: font(:lang=%{-f*})}%{!-f:%{-F:Requires: font(:lang=%{lang})}} \
%{-h:Requires: hunspell-%{-h*}}%{!-h:%{-H:Requires: hunspell-%{lang}}} \
%{-m:Requires: mythes-%{-m*}}%{!-m:%{-M:Requires: mythes-%{lang}}} \
%{-y:Requires: hyphen-%{-y*}}%{!-y:%{-Y:Requires: hyphen-%{lang}}} \
%{-r:Requires: %{-r*}} \
%{-o:Obsoletes: openoffice.org-langpack-%{-o*} < 1:3.3.1}%{!-o:%{-O:Obsoletes: openoffice.org-langpack-%{lang} < 1:3.3.1}} \
%{-w:Obsoletes: openoffice.org2-langpack-%{-x*} < 1:3.0.0}%{!-x:%{-W:Obsoletes: openoffice.org2-langpack-%{lang} < 1:3.0.0}} \
%{-v:Obsoletes: openoffice.org-langpack-%{-v*} < 1:2.0.3}%{!-v:%{-V:Obsoletes: openoffice.org-langpack-%{lang} < 1:2.0.3}} \
%{-p:Provides: %{name}-langpack-%{-p*} = %{epoch}:%{version}-%{release}} \
%{-p:Provides: %{name}-langpack-%{-p*}%{?_isa} = %{epoch}:%{version}-%{release}} \
%if 0%{?weak_deps} \
%{-p:Supplements: (%{name}-core%{?_isa} = %{epoch}:%{version}-%{release} and langpacks-%{-p*})} \
%{!-p:Supplements: (%{name}-core%{?_isa} = %{epoch}:%{version}-%{release} and langpacks-%{lang})} \
%endif \
\
%description %{pkgname} \
Provides additional %{langname} translations and resources for LibreOffice. \
\
%files %{pkgname} \
%{!-E: \
%{expand:%%_langpack_common %{_langpack_lang}} \
%{-x:%{baseinstdir}/share/autotext/%{-x*}}%{!-x:%{-X:%{baseinstdir}/share/autotext/%{_langpack_lang}}} \
%{-c:%{baseinstdir}/share/registry/%{-c*}.xcd} \
%{-s:%{baseinstdir}/share/registry/%{-s*}_%{_langpack_lang}.xcd} \
%{-T: \
%docdir %{baseinstdir}/help/%{_langpack_lang} \
%{baseinstdir}/help/%{_langpack_lang} \
} \
%{-i:%{expand:%%_langpack_common %{-i*}}} \
} \
%{nil}

# Defines an auto-correction subpackage.
#
# i: add autocorrections from additional language
# l: language code
# n: language name
# L  the filename does not contain country code
#
# All remaining arguments are considered to be files and added to the file
# list.
%define autocorr(i:Ll:n:) \
%define lang %{-l:%{-l*}}%{!-l:%{error:Language code not defined}} \
%define pkgname autocorr-%{lang} \
%define langname %{-n:%{-n*}}%{!-n:%{error:Language name not defined}} \
\
%package -n %{pkgname} \
Summary: %{langname} auto-correction rules \
BuildArch: noarch \
\
%description -n %{pkgname} \
Rules for auto-correcting common %{langname} typing errors. \
\
%files -n %{pkgname} \
%doc instdir/LICENSE \
%dir %{_datadir}/autocorr \
%{-L:%{_datadir}/autocorr/acor_%{lang}.dat} \
%{!-L:%{_datadir}/autocorr/acor_%{lang}-*.dat} \
%{-i:%{_datadir}/autocorr/acor_%{-i*}-*.dat} \
%{nil}

%langpack -l en -n English -F -h en-US -Y -M -A -E -L en-US -O



%langpack -l af -n Afrikaans -F -H -Y -A -o af_ZA -V -w af_ZA
%langpack -l ar -n Arabic -F -H -s ctl -O -W
%langpack -l as -n Assamese -F -H -Y -o as_IN -w as_IN
%langpack -l bg -n Bulgarian -F -H -Y -M -A -T -X -o bg_BG -V -w bg_BG
%langpack -l bn -n Bengali -F -H -Y -T -O -v bn_IN -W
%langpack -l br -n Breton -F -H
%langpack -l ca -n Catalan -F -H -Y -M -A -T -o ca_ES -V -w ca_ES -X
%langpack -l cs -n Czech -F -H -Y -M -A -T -X -o cs_CZ -V -w cs_CZ
%langpack -l cy -n Welsh -F -H -Y -o cy_GB -V -w cy_GB
%langpack -l da -n Danish -F -H -Y -M -A -T -X -o da_DK -V -w da_DK
%langpack -l de -n German -F -H -Y -M -A -T -X -O -W
%langpack -l dz -n Dzongkha -F -s ctl -T -O
%langpack -l el -n Greek -F -H -Y -M -T -o el_GR -V -w el_GR
%langpack -l es -n Spanish -F -H -Y -M -A -T -X -O -W
%langpack -l et -n Estonian -F -H -Y -T -o et_EE -V -w et_EE
%langpack -l eu -n Basque -F -H -Y -T -o eu_ES -V -w eu_ES
%langpack -l fa -n Farsi -A -H -Y -s ctl -X
%langpack -l fi -n Finnish -F -r libreoffice-voikko -A -T -o fi_FI -V -w fi_FI -X
%langpack -l fr -n French -F -H -Y -M -A -T -X -O -W
%langpack -l ga -n Irish -F -H -Y -M -A -o ga_IE -w ga_IE
%langpack -l gl -n Galician -F -H -Y -T -o gl_ES -V -w gl_ES
%langpack -l gu -n Gujarati -F -H -Y -s ctl -o gu_IN -w gu_IN -T
%langpack -l he -n Hebrew -F -H -s ctl -o he_IL -V -w he_IL -T
%langpack -l hi -n Hindi -F -H -Y -s ctl -T -o hi_IN -v hi-IN -w hi_IN -X
%langpack -l hr -n Croatian -F -H -Y -A -o hr_HR -V -w hr_HR -T -X
%langpack -l hu -n Hungarian -F -H -Y -M -A -T -X -o hu_HU -V -w hu_HU
%langpack -l it -n Italian -F -H -Y -M -A -T -X -O -W
%langpack -l ja -n Japanese -F -A -s cjk -T -X -o ja_JP -V -w ja_JP
%langpack -l kk -n Kazakh -F -H
%langpack -l kn -n Kannada -F -H -Y -o kn_IN -w ka_IN
%langpack -l ko -n Korean -F -H -A -s cjk -T -X -o ko_KR -V -w ko_KR
%langpack -l lt -n Lithuanian -F -H -Y -A -o lt_LT -V -w lt_LT -X
%langpack -l lv -n Latvian -F -H -Y -M
%langpack -l mai -n Maithili -F -o mai_IN
%langpack -l ml -n Malayalam -F -H -Y -o ml_IN -w ml_IN
%langpack -l mr -n Marathi -F -H -Y -o mr_IN -w mr_IN
%langpack -l nb -n Bokmal -F -H -Y -M -T -o nb_NO -V -w nb_NO
%langpack -l nl -n Dutch -F -H -Y -M -A -T -X -O -W
%langpack -l nn -n Nynorsk -F -H -Y -M -T -o nn_NO -V -w nn_NO
%define langpack_lang Southern Ndebele
%langpack -l nr -n %{langpack_lang} -F -H -o nr_ZA
%define langpack_lang Northern Sotho
%langpack -l nso -n %{langpack_lang} -F -H -o nso_ZA -w nso_ZA
%langpack -l or -n Odia -F -H -Y -s ctl -o or_IN -w or_IN
%langpack -l pa -n Punjabi -F -H -Y -s ctl -L pa-IN -O -v pa_IN -w pa_IN
%langpack -l pl -n Polish -F -H -Y -M -A -T -X -o pl_PL -V -w pl_PL
%define langpack_lang Brazilian Portuguese
%langpack -l pt-BR -n %{langpack_lang} -f pt -h pt -y pt -m pt -a pt -p pt_BR -T -X -o pt_BR -V -w pt_BR
%langpack -l pt-PT -n Portuguese -f pt -h pt -y pt -m pt -a pt -p pt_PT -T -L pt -x pt -o pt_PT -v pt -W
%langpack -l ro -n Romanian -A -F -H -Y -M -O -X
%langpack -l ru -n Russian -F -H -Y -M -A -T -X -O -W
%langpack -l si -n Sinhalese -F -H -S ctl -T -O
%langpack -l sk -n Slovak -F -H -Y -M -A -T -X -o sk_SK -V -w sk_SK
%langpack -l sl -n Slovenian -F -H -Y -M -A -T -X -o sl_SI -V -w sl_SI
%{baseinstdir}/share/wordbook/sl.dic

#rhbz#452379 clump serbian translations together
%langpack -l sr -n Serbian -F -H -Y -A -i sr-Latn -O -v sr_CS -w sr_CS
%langpack -l ss -n Swati -F -H -o ss_ZA
%define langpack_lang Southern Sotho
%langpack -l st -n %{langpack_lang} -F -H -o st_ZA
%langpack -l sv -n Swedish -F -H -Y -M -A -T -X -O -W
%langpack -l ta -n Tamil -F -H -Y -s ctl -o ta_IN -w ta_IN
%langpack -l te -n Telugu -F -H -Y -o te_IN -w te_IN
%langpack -l th -n Thai -F -H -s ctl -c ctlseqcheck_th -o th_TH -V -w th_TH
%langpack -l tn -n Tswana -F -H -o tn_ZA -V -w tn_ZA
%langpack -l tr -n Turkish -F -A -T -X -o tr_TR -V -W
%langpack -l ts -n Tsonga -F -H -o ts_ZA -V -w ts_ZA
%langpack -l uk -n Ukrainian -F -H -Y -M -T -O
%langpack -l ve -n Venda -F -H -o ve_ZA
%langpack -l xh -n Xhosa -F -H -o xh_ZA
%define langpack_lang Simplified Chinese
%langpack -l zh-Hans -n %{langpack_lang} -f zh-cn -a zh -p zh_CN -s cjk -T -L zh-CN -x zh-CN -o zh_CN -v zh-CN -w zh_CN
%define langpack_lang Traditional Chinese
%langpack -l zh-Hant -n %{langpack_lang} -f zh-tw -a zh -p zh_TW -s cjk -T -L zh-TW -x zh-TW -o zh_TW -v zh-TW -w zh_TW
%langpack -l zu -n Zulu -F -H -Y -o zu_ZA -V -w zu_ZA
%undefine langpack_lang



%autocorr -l en -n English



%autocorr -l af -n Afrikaans
%autocorr -l bg -n Bulgarian
%autocorr -l ca -n Catalan
%autocorr -l cs -n Czech
%autocorr -l da -n Danish
%autocorr -l de -n German -L
%autocorr -l es -n Spanish -L
%autocorr -l fa -n Farsi
%autocorr -l fi -n Finnish
%autocorr -l fr -n French -L
%autocorr -l ga -n Irish
%autocorr -l hr -n Croatian
%autocorr -l hu -n Hungarian
%autocorr -l is -n Icelandic
%autocorr -l it -n Italian -L
%autocorr -l ja -n Japanese
%autocorr -l ko -n Korean
%autocorr -l lb -n Luxembourgish
%autocorr -l lt -n Lithuanian
%autocorr -l mn -n Mongolian
%autocorr -l nl -n Dutch
%autocorr -l pl -n Polish
%autocorr -l pt -n Portuguese
%autocorr -l ro -n Romanian
%autocorr -l ru -n Russian
%autocorr -l sk -n Slovak
%autocorr -l sl -n Slovenian
#rhbz#452379 clump serbian autocorrections together
%autocorr -l sr -n Serbian -i sr-Latn -i sr
%autocorr -l sv -n Swedish
%autocorr -l tr -n Turkish
%autocorr -l vi -n Vietnamese
%autocorr -l zh -n Chinese



%define make_autocorr_aliases(l:) \
%{?-l: \
for lang in %{*}; do \
    ln -sf acor_%{-l*}.dat acor_$lang.dat \
done \
} \
%{!?-l:%{error:-l must be present}}

%prep
%setup -q -n %{name}-%{version}%{?libo_prerelease} -b 1 -b 2
rm -rf git-hooks */git-hooks

# set up git repo
git init
git config user.name rpmbuild
git config user.email rpmbuild@fedoraproject.org
git config gc.auto 0 # disable auto packing
git add -A
git commit -q -a -m %{name}-%{version}

#Customize Palette to add Red Hat colours
(head -n -1 extras/source/palettes/standard.soc && \
 echo -e '  <draw:color draw:name="Red Hat 1" draw:color="#cc0000"/>
  <draw:color draw:name="Red Hat 2" draw:color="#0093d9"/>
  <draw:color draw:name="Red Hat 3" draw:color="#ff8d00"/>
  <draw:color draw:name="Red Hat 4" draw:color="#abb400"/>
  <draw:color draw:name="Red Hat 5" draw:color="#4e376b"/>' && \
 tail -n 1 extras/source/palettes/standard.soc) > redhat.soc
mv -f redhat.soc extras/source/palettes/standard.soc
git commit -q -a -m 'add Red Hat colors to palette'

# apply patches
git am %{patches}

sed -i -e /CppunitTest_sw_ooxmlexport7/d sw/Module_sw.mk
sed -i -e /CppunitTest_sd_import_tests/d sd/Module_sd.mk
git commit -q -a -m 'temporarily disable failing tests'

# Seeing .git dir makes some of the build tools change their behavior.
# We do not want that. Note: it is still possible to use
# git --git-dir=.git-rpm
mv .git .git-rpm

%build
echo build start time is `date`, diskspace: `df -h . | tail -n 1`
echo building localizations: %{langpack_langs}
# path to external tarballs
EXTSRCDIR=`dirname %{SOURCE0}`

%if 0%{?fedora}
# KDE bits
export QT4DIR=%{_qt4_prefix}
export KDE4DIR=%{_kde4_prefix}
export PATH=$QT4DIR/bin:$PATH
%endif

#use the RPM_OPT_FLAGS but remove the OOo overridden ones
for i in $RPM_OPT_FLAGS; do
        case "$i" in
                -pipe|-Wall|-Werror*|-g|-fexceptions) continue;;
        esac
        ARCH_FLAGS="$ARCH_FLAGS $i"
done
%ifarch s390 aarch64
# these builders typically do not have enough memory to link the big libs with -g2
ARCH_FLAGS="$ARCH_FLAGS -g1"
%endif
export ARCH_FLAGS
export CFLAGS=$ARCH_FLAGS
export CXXFLAGS=$ARCH_FLAGS

%if 0%{?rhel}
%define distrooptions --disable-eot --disable-gltf --disable-firebird-sdbc --enable-python=system --disable-introspection --disable-gtk3
%else # fedora
%define distrooptions --enable-eot --enable-gtk3 --enable-kde4 --with-system-opencollada --with-system-ucpp
export OPENCOLLADA_CFLAGS='-I/usr/include/COLLADABaseUtils -I/usr/include/COLLADAFramework -I/usr/include/COLLADASaxFrameworkLoader -I/usr/include/GeneratedSaxParser'
export OPENCOLLADA_LIBS='-lOpenCOLLADABaseUtils -lOpenCOLLADAFramework -lOpenCOLLADASaxFrameworkLoader -lGeneratedSaxParser'
%endif


%define with_lang --with-lang='%{langpack_langs}'


%if ! 0%{libo_use_python3}
export PYTHON=%{_bindir}/python
export PYTHON_CFLAGS=`pkg-config --cflags python`
export PYTHON_LIBS=`pkg-config --libs python`
%endif


export MDDS_CFLAGS=`pkg-config --cflags mdds-1.0`
export MDDS_LIBS=' '


aclocal -I m4
autoconf

# TODO: enable coinmp?
# avoid running autogen.sh on make
touch autogen.lastrun
%configure \
 %vendoroption \
 %{?with_lang} \
 %{?_smp_mflags:--with-parallelism=%{_smp_mflags}} \
 --disable-coinmp \
 --disable-fetch-external \
 --with-system-openssl \
 --disable-systray \
 --enable-evolution2 \
 --enable-ext-nlpsolver \
 --enable-ext-wiki-publisher \
 --enable-release-build \
 --enable-scripting-beanshell \
 --enable-scripting-javascript \
 --enable-symbols \
 --with-build-version="%{version}-%{release}" \
 --with-external-dict-dir=/usr/share/myspell \
 --with-external-tar="$EXTSRCDIR" \
 --with-help \
 --with-system-dicts \
 --with-system-libs \
 --without-fonts \
 --without-system-npapi-headers \
 --with-gdrive-client-secret="GYWrDtzyZQZ0_g5YoBCC6F0I" \
 --with-gdrive-client-id="457862564325.apps.googleusercontent.com" \
 %{distrooptions} \
 %{?bundling_options} \
 %{?archoptions}

ulimit -c unlimited
 make verbose=true build-nocheck

#generate the icons and mime type stuff
export DESTDIR=../output
export KDEMAINDIR=/usr
export GNOMEDIR=/usr
export GNOME_MIME_THEME=hicolor
export PREFIXDIR=/usr
# TODO use empty variables? Should make the renaming hacks in %%install
# unnecessary.
. ./bin/get_config_variables PRODUCTVERSIONSHORT PRODUCTVERSION SRCDIR WORKDIR PKG_CONFIG INSTDIR
pushd $WORKDIR/CustomTarget/sysui/share/libreoffice
./create_tree.sh
popd
mkdir $WORKDIR/os-integration
cp -pr $WORKDIR/CustomTarget/sysui/share/output/usr/share/* $WORKDIR/os-integration
%if 0%{?fedora}
cp -pr $WORKDIR/CustomTarget/sysui/share/output/girepository-1.0/LOKDocView-%{girapiversion}.* $WORKDIR/os-integration
%endif

%if %{with smallbuild}
# remove the biggest offenders
# NOTE: not removing complete LinkTarget, as some libs are needed for smoketest
rm -rf $WORKDIR/CxxObject $WORKDIR/GenCxxObject $WORKDIR/HelpTarget $WORKDIR/LinkTarget/CppunitTest
%endif

echo build end time is `date`, diskspace: `df -h . | tail -n 1`


%install
# TODO investigate use of make distro-pack-install
#figure out the icon version
. ./bin/get_config_variables PRODUCTVERSIONSHORT PRODUCTVERSION SRCDIR WORKDIR
export PRODUCTVERSIONSHORT PRODUCTVERSION

# installation

install -m 0755 -d %{buildroot}%{instdir}
if ! make instsetoo_native PKGFORMAT=installed EPM=not-used-but-must-be-set; then
    echo - ---dump log start---
    cat $WORKDIR/installation/LibreOffice/installed/logging/en-US/log_*_en-US.log
    echo - ---dump log end---
    echo - ---dump log start -- SDK---
    cat $WORKDIR/installation/LibreOffice_SDK/installed/logging/en-US/log_*_en-US.log
    echo - ---dump log end -- SDK---
    echo - ---dump log start -- languagepacks---
    cat $WORKDIR/installation/LibreOffice_languagepack/installed/logging/en-US/log_*_en-US.log
    echo - ---dump log end -- languagepacks---
    exit 1
fi
install -m 0755 -d %{buildroot}%{baseinstdir}
mv $WORKDIR/installation/LibreOffice/installed/install/en-US/* %{buildroot}%{baseinstdir}

for langpack in $WORKDIR/installation/LibreOffice_languagepack/installed/install/*; do
  [ `basename $langpack` = log ] && continue
  cp -rp $langpack/* %{buildroot}%{baseinstdir}
  rm -rf $langpack
done

mv $WORKDIR/installation/LibreOffice_SDK/installed/install/en-US/sdk %{buildroot}%{sdkinstdir}
chmod -R +w %{buildroot}%{baseinstdir}

# postprocessing and tweaks

# The installer currently sets UserInstallation to
# $ORIGIN/../libreoffice/4, which is of course total nonsense. Because I
# have no inclination to crawl through mountains of perl code to figure out
# where it comes from, I am just going to replace it by a sensible
# value here.
sed -i -e '/UserInstallation/s@\$ORIGIN/..@$SYSUSERCONFIG@' %{buildroot}%{baseinstdir}/program/bootstraprc

#configure sdk
pushd %{buildroot}%{sdkinstdir}
    sed -e "s,@OO_SDK_NAME@,sdk," \
        -e "s,@OO_SDK_HOME@,%{sdkinstdir}," \
        -e "s,@OFFICE_HOME@,%{baseinstdir}," \
        -e "s,@OO_SDK_MAKE_HOME@,/usr/bin," \
        -e "s,@OO_SDK_ZIP_HOME@,/usr/bin," \
        -e "s,@OO_SDK_CPP_HOME@,/usr/bin," \
        -e "s,@OO_SDK_CAT_HOME@,/usr/bin," \
        -e "s,@OO_SDK_SED_HOME@,/usr/bin," \
        -e "s,@OO_SDK_CC_55_OR_HIGHER@,," \
        -e "s,@OO_SDK_JAVA_HOME@,$JAVA_HOME," \
        -e "s,@OO_SDK_OUTPUT_DIR@,\$HOME," \
        -e "s,@SDK_AUTO_DEPLOYMENT@,NO," \
        setsdkenv_unix.sh.in > setsdkenv_unix.sh
    # ensure no unexpanded vars sneaked in
    grep '@[A_Z0-9_]\+@' setsdkenv_unix.sh && exit 1
    chmod 755 setsdkenv_unix.sh
    # we don't want to install the input file
    rm -f setsdkenv_unix.sh.in
# TODO: is this still necessary?
#fix permissions
    find examples -type f -exec chmod -x {} \;
popd

#ensure a template dir for each lang
pushd %{buildroot}%{baseinstdir}/share/template
for I in %{langpack_langs}; do
    mkdir -p $I
done
popd

#Set some aliases to canonical autocorrect language files for locales with matching languages
pushd %{buildroot}%{baseinstdir}/share/autocorr

%make_autocorr_aliases -l en-GB en-AG en-AU en-BS en-BW en-BZ en-CA en-DK en-GH en-HK en-IE en-IN en-JM en-NG en-NZ en-SG en-TT
%make_autocorr_aliases -l en-US en-PH
#en-ZA exists and has a good autocorrect file with two or three extras that make sense for 
#neighbouring english speaking territories
%make_autocorr_aliases -l en-ZA en-NA en-ZW

%make_autocorr_aliases -l af-ZA af-NA
%make_autocorr_aliases -l nl-NL nl-AW
%make_autocorr_aliases -l sv-SE sv-FI

popd
#rhbz#484055 make these shared across multiple applications
install -m 0755 -d %{buildroot}%{_datadir}
mv -f %{buildroot}%{baseinstdir}/share/autocorr %{buildroot}%{_datadir}/autocorr
chmod 755 %{buildroot}%{_datadir}/autocorr
ln -s %{_datadir}/autocorr %{buildroot}%{baseinstdir}/share/autocorr

#remove it in case we didn't build with gcj
rm -f %{buildroot}%{baseinstdir}/program/classes/sandbox.jar

#remove dummy .dat files
rm -f %{buildroot}%{baseinstdir}/program/root?.dat

# I don't think we need this...
rm -f %{buildroot}%{baseinstdir}/share/classification/example*.xml
rmdir %{buildroot}%{baseinstdir}/share/classification

#set standard permissions for rpmlint
find %{buildroot}%{baseinstdir} -exec chmod +w {} \;
find %{buildroot}%{baseinstdir} -type d -exec chmod 0755 {} \;

# move python bits into site-packages
install -m 0755 -d %{buildroot}%{libo_python_sitearch}
pushd %{buildroot}%{libo_python_sitearch}
echo "import sys, os" > uno.py
echo "sys.path.append('%{baseinstdir}/program')" >> uno.py
echo "os.putenv('URE_BOOTSTRAP', 'vnd.sun.star.pathname:%{baseinstdir}/program/fundamentalrc')" >> uno.py
cat %{buildroot}%{baseinstdir}/program/uno.py >> uno.py
rm -f %{buildroot}%{baseinstdir}/program/uno.py*
mv -f %{buildroot}%{baseinstdir}/program/unohelper.py* .
mv -f %{buildroot}%{baseinstdir}/program/officehelper.py* .
popd

# rhbz#477435 package opensymbol separately
pushd %{buildroot}%{baseinstdir}/share/fonts/truetype
install -d -m 0755 %{buildroot}%{_fontdir}
install -p -m 0644 *.ttf %{buildroot}%{_fontdir}
popd
rm -rf %{buildroot}%{baseinstdir}/share/fonts

# move platform-independent data into shared dir
install -m 0755 -d %{buildroot}%{datadir}
rm -f %{buildroot}%{baseinstdir}/CREDITS.fodt %{buildroot}%{baseinstdir}/LICENSE* %{buildroot}%{baseinstdir}/NOTICE

#ensure that no sneaky un-prelinkable, un-fpic or non executable shared libs 
#have snuck through
pic=0
executable=0
for foo in `find %{buildroot}%{instdir} -name "*" -exec file {} \;| grep ": ELF" | cut -d: -f 1` ; do
    chmod +wx $foo
    ls -asl $foo
    result=`readelf -d $foo | grep TEXTREL` || true
    if [ "$result" != "" ]; then
        echo "TEXTREL Warning: $foo is b0rked (-fpic missing)"
        pic=1
    fi
    result=`readelf -l $foo | grep GNU_STACK | grep RWE` || true
    if [ "$result" != "" ]; then
        echo "GNU_STACK Warning: $foo is b0rked (-noexecstack missing)"
        executable=1
    fi
done
if [ $pic == 1 ]; then false; fi
if [ $executable == 1 ]; then false; fi

#make up some /usr/bin scripts
install -m 0755 -d %{buildroot}%{_bindir}

pushd %{buildroot}%{_bindir}
echo \#\!/bin/sh > ooffice
echo exec libreoffice \"\$@\" >> ooffice
chmod a+x ooffice

echo \#\!/bin/sh > ooviewdoc
echo exec libreoffice --view \"\$@\" >> ooviewdoc
chmod a+x ooviewdoc

for app in base calc draw impress math writer; do
    echo \#\!/bin/sh > oo$app
    echo exec libreoffice --$app \"\$@\" >> oo$app
    chmod a+x oo$app
done

sed -e s/LAUNCHER/unopkg/g -e s/BRAND/libreoffice/g %{SOURCE4} > unopkg
chmod a+x unopkg

sed -e s/LAUNCHER/soffice/g -e s/BRAND/libreoffice/g %{SOURCE4} > libreoffice
chmod a+x libreoffice

# rhbz#499474 provide a /usr/bin/soffice for .recently-used.xbel
ln -s %{baseinstdir}/program/soffice soffice
# rhbz#499474 provide a /usr/bin/openoffice.org for backwards compat
ln -s libreoffice openoffice.org
popd

pushd %{buildroot}%{baseinstdir}/share/xdg/
chmod u+w *.desktop
ICONVERSION=`echo $PRODUCTVERSION | sed -e 's/\.//'`
for file in *.desktop; do
    # rhbz#156677 remove the version from Name=
    # rhbz#156067 don't version the icons
    sed -i -e "s/ *$PRODUCTVERSION//g" \
        -e "s/$ICONVERSION//g" \
        -e "s/$PRODUCTVERSIONSHORT//g" \
        $file
done
# rhbz#156677 / rhbz#186515 do not show math and startcenter
sed -i -e /NoDisplay/s/false/true/ math.desktop startcenter.desktop
# relocate the .desktop and icon files
install -m 0755 -d %{buildroot}%{_datadir}/applications
for app in base calc draw impress math startcenter writer xsltfilter; do
    sed -i -e 's/\${UNIXBASISROOTNAME}/%{name}/' $app.desktop
    desktop-file-validate $app.desktop
    install -m 0644 -p $app.desktop %{buildroot}%{_datadir}/applications/libreoffice-$app.desktop
done
popd

pushd $WORKDIR/os-integration
#get rid of the gnome icons and other unneeded files
rm -rf icons/gnome applications application-registry

#relocate the rest of them
# rhbz#901346 512x512 icons are not used by anything
for icon in `find icons -path '*/512x512' -prune -o -type f -print`; do
    install -m 0755 -d %{buildroot}%{_datadir}/`dirname $icon`
    install -m 0644 -p $icon %{buildroot}%{_datadir}/`echo $icon | sed -e s@libreoffice$ICONVERSION-@libreoffice-@ | sed -e s@libreoffice$PRODUCTVERSION-@libreoffice-@`
done
install -m 0755 -d %{buildroot}%{_datadir}/mime-info
install -m 0644 -p mime-info/libreoffice$PRODUCTVERSION.keys %{buildroot}%{_datadir}/mime-info/libreoffice.keys
install -m 0644 -p mime-info/libreoffice$PRODUCTVERSION.mime %{buildroot}%{_datadir}/mime-info/libreoffice.mime
#add our mime-types, e.g. for .oxt extensions
install -m 0755 -d %{buildroot}%{_datadir}/mime/packages
install -m 0644 -p mime/packages/libreoffice$PRODUCTVERSION.xml %{buildroot}%{_datadir}/mime/packages/libreoffice.xml
install -m 0755 -d %{buildroot}%{_libdir}/girepository-1.0
%if 0%{?fedora}
install -m 0644 -p LOKDocView-%{girapiversion}.typelib %{buildroot}%{_libdir}/girepository-1.0/LOKDocView-%{girapiversion}.typelib
install -m 0755 -d %{buildroot}%{_libdir}/gir-1.0
install -m 0644 -p gir-1.0/LOKDocView-%{girapiversion}.gir %{buildroot}%{_libdir}/gir-1.0/LOKDocView-%{girapiversion}.gir
mv %{buildroot}%{baseinstdir}/program/liblibreofficekitgtk.so %{buildroot}%{_libdir}
%endif
popd

rm -rf %{buildroot}%{baseinstdir}/readmes
rm -rf %{buildroot}%{baseinstdir}/licenses

# to-do, remove this in libreoffice 4.4 when --without-ppds is gone, it'll do the right thing on its own then
install -m 0755 -d %{buildroot}%{baseinstdir}/share/psprint/driver
install -m 0644 -p vcl/unx/generic/printer/configuration/ppds/SGENPRT.PS %{buildroot}%{baseinstdir}/share/psprint/driver/SGENPRT.PS

# rhbz#452385 to auto have postgres in classpath if subsequently installed
sed -i -e "s#URE_MORE_JAVA_CLASSPATH_URLS.*#& file:///usr/share/java/postgresql-jdbc.jar#" %{buildroot}%{baseinstdir}/program/fundamentalrc

# move glade catalog to system glade dir
install -m 0755 -d %{buildroot}%{_datadir}/glade/catalogs
mv %{buildroot}%{baseinstdir}/share/glade/libreoffice-catalog.xml %{buildroot}%{_datadir}/glade/catalogs
install -m 0755 -d %{buildroot}%{_datadir}/glade3/catalogs
ln -sr %{buildroot}%{_datadir}/glade/catalogs/libreoffice-catalog.xml %{buildroot}%{_datadir}/glade3/catalogs

# rhbz#1049543 install appdata
install -m 0755 -d %{buildroot}%{_datadir}/appdata
install -m 0644 -p sysui/desktop/appstream-appdata/*.appdata.xml %{buildroot}%{_datadir}/appdata

# rhbz#1215800 install symbolic icons
install -m 0755 -d %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps
install -m 0644 -p %{SOURCE42} %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps
install -m 0644 -p %{SOURCE43} %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps
install -m 0644 -p %{SOURCE44} %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps
install -m 0644 -p %{SOURCE45} %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps
install -m 0644 -p %{SOURCE46} %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps
install -m 0644 -p %{SOURCE47} %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps
install -m 0644 -p %{SOURCE48} %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps

# install man pages
install -m 0755 -d %{buildroot}%{_mandir}/man1
install -m 0644 -p sysui/desktop/man/*.1 %{buildroot}%{_mandir}/man1
for app in oobase oocalc oodraw ooffice ooimpress oomath ooviewdoc oowriter openoffice.org soffice; do
    echo '.so man1/libreoffice.1' > $app.1
    install -m 0644 -p $app.1 %{buildroot}%{_mandir}/man1
done

export DESTDIR=%{buildroot}
./solenv/bin/install-gdb-printers -a %{_datadir}/gdb/auto-load%{baseinstdir} -c -i %{baseinstdir} -p %{_datadir}/libreoffice/gdb

%if 0%{?fedora}
# Update the screenshot shown in the software center
#
# NOTE: It would be *awesome* if this file was pushed upstream.
#
# See http://people.freedesktop.org/~hughsient/appdata/#screenshots for more details.
#
appstream-util replace-screenshots %{buildroot}%{_datadir}/appdata/libreoffice-writer.appdata.xml \
  https://raw.githubusercontent.com/hughsie/fedora-appstream/master/screenshots-extra/libreoffice-writer/a.png \
  https://raw.githubusercontent.com/hughsie/fedora-appstream/master/screenshots-extra/libreoffice-writer/b.png 
appstream-util replace-screenshots %{buildroot}%{_datadir}/appdata/libreoffice-calc.appdata.xml \
  https://raw.githubusercontent.com/hughsie/fedora-appstream/master/screenshots-extra/libreoffice-calc/a.png 
appstream-util replace-screenshots %{buildroot}%{_datadir}/appdata/libreoffice-draw.appdata.xml \
  https://raw.githubusercontent.com/hughsie/fedora-appstream/master/screenshots-extra/libreoffice-draw/a.png 
appstream-util replace-screenshots %{buildroot}%{_datadir}/appdata/libreoffice-impress.appdata.xml \
  https://raw.githubusercontent.com/hughsie/fedora-appstream/master/screenshots-extra/libreoffice-impress/a.png 
%endif

%check
unset WITH_LANG
# work around flawed accessibility check
export JFW_PLUGIN_DO_NOT_CHECK_ACCESSIBILITY="1"
export OOO_TEST_SOFFICE=path:%{buildroot}%{baseinstdir}/program/soffice
# timeout -k 2m 2h make smoketest.subsequentcheck
# we don't need this anymore
rm -f %{buildroot}%{baseinstdir}/program/classes/smoketest.jar

%files

%files filters

%files core
%dir %{baseinstdir}
%dir %{baseinstdir}/help
%docdir %{baseinstdir}/help/en-US
%dir %{baseinstdir}/help/en-US
%{baseinstdir}/help/en-US/default.css
%{baseinstdir}/help/en-US/err.html
%{baseinstdir}/help/en-US/highcontrast1.css
%{baseinstdir}/help/en-US/highcontrast2.css
%{baseinstdir}/help/en-US/highcontrastblack.css
%{baseinstdir}/help/en-US/highcontrastwhite.css
%{baseinstdir}/help/en-US/sbasic.*
%{baseinstdir}/help/en-US/schart.*
%{baseinstdir}/help/en-US/shared.*
%{baseinstdir}/help/idxcaption.xsl
%{baseinstdir}/help/idxcontent.xsl
%{baseinstdir}/help/main_transform.xsl
%{baseinstdir}/presets
%dir %{baseinstdir}/program
%{baseinstdir}/program/libbasprovlo.so
%{baseinstdir}/program/libcairocanvaslo.so
%{baseinstdir}/program/libcanvasfactorylo.so
%dir %{baseinstdir}/program/classes
%{baseinstdir}/program/classes/commonwizards.jar
%{baseinstdir}/program/classes/form.jar
%{baseinstdir}/program/classes/query.jar
%{baseinstdir}/program/classes/report.jar
%{baseinstdir}/program/classes/ScriptFramework.jar
%{baseinstdir}/program/classes/ScriptProviderForJava.jar
%{baseinstdir}/program/classes/table.jar
%{baseinstdir}/program/classes/unoil.jar
%{baseinstdir}/program/classes/XMergeBridge.jar
%{baseinstdir}/program/classes/xmerge.jar
%{baseinstdir}/program/libcmdmaillo.so
%{baseinstdir}/program/libdeployment.so
%{baseinstdir}/program/libdeploymentgui.so
%{baseinstdir}/program/libdlgprovlo.so
%{baseinstdir}/program/libexpwraplo.so
%{baseinstdir}/program/flat_logo.svg
%{baseinstdir}/program/libfps_officelo.so
%{baseinstdir}/program/gdbtrace
%{baseinstdir}/program/gengal
%{baseinstdir}/program/gengal.bin
%{baseinstdir}/program/libi18nsearchlo.so
%{baseinstdir}/program/libldapbe2lo.so
%{baseinstdir}/program/libacclo.so
%{baseinstdir}/program/libavmedia*.so
%{baseinstdir}/program/libbasctllo.so
%{baseinstdir}/program/libbiblo.so
%{baseinstdir}/program/libcached1.so
%{baseinstdir}/program/libcanvastoolslo.so
%{baseinstdir}/program/libchart*lo.so
%{baseinstdir}/program/libclewlo.so
%{baseinstdir}/program/libcollator_data.so
%{baseinstdir}/program/libcppcanvaslo.so
%{baseinstdir}/program/libctllo.so
%{baseinstdir}/program/libcuilo.so
%{baseinstdir}/program/libdbalo.so
%{baseinstdir}/program/libdbaselo.so
%{baseinstdir}/program/libdbaxmllo.so
%{baseinstdir}/program/libdbmmlo.so
%{baseinstdir}/program/libdbpool2.so
%{baseinstdir}/program/libdbtoolslo.so
%{baseinstdir}/program/libdbulo.so
%{baseinstdir}/program/libdeploymentmisclo.so
%{baseinstdir}/program/libdesktop_detectorlo.so
%{baseinstdir}/program/libdict_ja.so
%{baseinstdir}/program/libdict_zh.so
%{baseinstdir}/program/libdrawinglayerlo.so
%{baseinstdir}/program/libeditenglo.so
%{baseinstdir}/program/libembobj.so
%{baseinstdir}/program/libemboleobj.so
%{baseinstdir}/program/libevoab*.so
%{baseinstdir}/program/libevtattlo.so
%{baseinstdir}/program/libgielo.so
%if 0%{?fedora}
%{baseinstdir}/program/libfirebird_sdbclo.so
%endif
%{baseinstdir}/program/libicglo.so
%{baseinstdir}/program/libindex_data.so
%{baseinstdir}/program/libfilelo.so
%{baseinstdir}/program/libfilterconfiglo.so
%{baseinstdir}/program/libflatlo.so
%{baseinstdir}/program/libfrmlo.so
%{baseinstdir}/program/libguesslanglo.so
%{baseinstdir}/program/libhelplinkerlo.so
%{baseinstdir}/program/libhyphenlo.so
%{baseinstdir}/program/libjdbclo.so
%{baseinstdir}/program/liblnglo.so
%{baseinstdir}/program/libloglo.so
%{baseinstdir}/program/liblocaledata_en.so
%{baseinstdir}/program/liblocaledata_es.so
%{baseinstdir}/program/liblocaledata_euro.so
%{baseinstdir}/program/liblocaledata_others.so
%{baseinstdir}/program/libmcnttype.so
%{baseinstdir}/program/libmorklo.so
%{baseinstdir}/program/libmozbootstraplo.so
%{baseinstdir}/program/libmsfilterlo.so
%{baseinstdir}/program/libmtfrendererlo.so
%{baseinstdir}/program/libmysqllo.so
%{baseinstdir}/program/libodbclo.so
%{baseinstdir}/program/liboglcanvaslo.so
%{baseinstdir}/program/liboffacclo.so
%{baseinstdir}/program/libooxlo.so
%{baseinstdir}/program/libopencllo.so
%{baseinstdir}/program/libpcrlo.so
%{baseinstdir}/program/libpdffilterlo.so
%{baseinstdir}/program/libprotocolhandlerlo.so
%{baseinstdir}/program/librecentfile.so
%{baseinstdir}/program/libreslo.so
%{baseinstdir}/program/libsaxlo.so
%{baseinstdir}/program/libscnlo.so
%{baseinstdir}/program/libscriptframe.so
%{baseinstdir}/program/libsdlo.so
%{baseinstdir}/program/libsdfiltlo.so
%{baseinstdir}/program/libsdbc2.so
%{baseinstdir}/program/libsdbtlo.so
%{baseinstdir}/program/libsddlo.so
%{baseinstdir}/program/libsduilo.so
%{baseinstdir}/program/libspelllo.so
%{baseinstdir}/program/libsrtrs1.so
%{baseinstdir}/program/libstoragefdlo.so
%{baseinstdir}/program/libsvgiolo.so
%{baseinstdir}/program/libsvxlo.so
%{baseinstdir}/program/libsvxcorelo.so
%{baseinstdir}/program/libswdlo.so
%{baseinstdir}/program/libswlo.so
%{baseinstdir}/program/libtextconv_dict.so
%{baseinstdir}/program/libtextconversiondlgslo.so
%{baseinstdir}/program/libtextfdlo.so
%{baseinstdir}/program/libodfflatxmllo.so
# TODO: shouldn't it have lo suffix?
%{baseinstdir}/program/libucbhelper.so
%{baseinstdir}/program/libucpchelp1.so
%{baseinstdir}/program/libucpdav1.so
%{baseinstdir}/program/libucpftp1.so
%{baseinstdir}/program/libucphier1.so
%{baseinstdir}/program/libucppkg1.so
%{baseinstdir}/program/libunordflo.so
%{baseinstdir}/program/libunopkgapp.so
%{baseinstdir}/program/libunoxmllo.so
%{baseinstdir}/program/libuuilo.so
%{baseinstdir}/program/libvbahelperlo.so
%{baseinstdir}/program/libxmlfalo.so
%{baseinstdir}/program/libxmlfdlo.so
%{baseinstdir}/program/libxoflo.so
%{baseinstdir}/program/libxsec_fw.so
%{baseinstdir}/program/libxsec_xmlsec.so
%{baseinstdir}/program/libxsltdlglo.so
%{baseinstdir}/program/libxsltfilterlo.so
%{baseinstdir}/program/libxstor.so
# TODO how useful this is in Fedora?
%{baseinstdir}/program/liblosessioninstalllo.so
%{baseinstdir}/program/libmigrationoo2lo.so
%{baseinstdir}/program/libmigrationoo3lo.so
%{baseinstdir}/program/libmsformslo.so
%{baseinstdir}/program/opencl
%dir %{baseinstdir}/program/opengl
%{baseinstdir}/program/opengl/areaHashCRC64TFragmentShader.glsl
%{baseinstdir}/program/opengl/areaScaleFragmentShader.glsl
%{baseinstdir}/program/opengl/areaScaleFastFragmentShader.glsl
%{baseinstdir}/program/opengl/backgroundFragmentShader.glsl
%{baseinstdir}/program/opengl/backgroundVertexShader.glsl
%{baseinstdir}/program/opengl/blendedTextureFragmentShader.glsl
%{baseinstdir}/program/opengl/blendedTextureVertexShader.glsl
%{baseinstdir}/program/opengl/combinedFragmentShader.glsl
%{baseinstdir}/program/opengl/combinedTextureFragmentShader.glsl
%{baseinstdir}/program/opengl/combinedTextureVertexShader.glsl
%{baseinstdir}/program/opengl/combinedVertexShader.glsl
%{baseinstdir}/program/opengl/commonFragmentShader.glsl
%{baseinstdir}/program/opengl/commonVertexShader.glsl
%{baseinstdir}/program/opengl/convolutionFragmentShader.glsl
%{baseinstdir}/program/opengl/debugFragmentShader.glsl
%{baseinstdir}/program/opengl/debugVertexShader.glsl
%{baseinstdir}/program/opengl/diffTextureFragmentShader.glsl
%{baseinstdir}/program/opengl/dumbVertexShader.glsl
%{baseinstdir}/program/opengl/dummyVertexShader.glsl
%{baseinstdir}/program/opengl/greyscaleFragmentShader.glsl
%{baseinstdir}/program/opengl/invert50FragmentShader.glsl
%{baseinstdir}/program/opengl/lineFragmentShader.glsl
%{baseinstdir}/program/opengl/lineVertexShader.glsl
%{baseinstdir}/program/opengl/linearGradientFragmentShader.glsl
%{baseinstdir}/program/opengl/linearMultiColorGradientFragmentShader.glsl
%{baseinstdir}/program/opengl/linearTwoColorGradientFragmentShader.glsl
%{baseinstdir}/program/opengl/maskedTextureFragmentShader.glsl
%{baseinstdir}/program/opengl/maskedTextureVertexShader.glsl
%{baseinstdir}/program/opengl/maskFragmentShader.glsl
%{baseinstdir}/program/opengl/pickingFragmentShader.glsl
%{baseinstdir}/program/opengl/pickingVertexShader.glsl
%{baseinstdir}/program/opengl/radialGradientFragmentShader.glsl
%{baseinstdir}/program/opengl/radialMultiColorGradientFragmentShader.glsl
%{baseinstdir}/program/opengl/radialTwoColorGradientFragmentShader.glsl
%{baseinstdir}/program/opengl/rectangularMultiColorGradientFragmentShader.glsl
%{baseinstdir}/program/opengl/rectangularTwoColorGradientFragmentShader.glsl
%{baseinstdir}/program/opengl/renderTextureFragmentShader.glsl
%{baseinstdir}/program/opengl/renderTextureVertexShader.glsl
%{baseinstdir}/program/opengl/replaceColorFragmentShader.glsl
%{baseinstdir}/program/opengl/screenTextFragmentShader.glsl
%{baseinstdir}/program/opengl/screenTextVertexShader.glsl
%{baseinstdir}/program/opengl/shape3DFragmentShader.glsl
%{baseinstdir}/program/opengl/shape3DFragmentShaderBatch.glsl
%{baseinstdir}/program/opengl/shape3DFragmentShaderBatchScroll.glsl
%{baseinstdir}/program/opengl/shape3DFragmentShaderV300.glsl
%{baseinstdir}/program/opengl/shape3DVertexShader.glsl
%{baseinstdir}/program/opengl/shape3DVertexShaderBatch.glsl
%{baseinstdir}/program/opengl/shape3DVertexShaderBatchScroll.glsl
%{baseinstdir}/program/opengl/shape3DVertexShaderV300.glsl
%{baseinstdir}/program/opengl/solidFragmentShader.glsl
%{baseinstdir}/program/opengl/symbolFragmentShader.glsl
%{baseinstdir}/program/opengl/symbolVertexShader.glsl
%{baseinstdir}/program/opengl/textFragmentShader.glsl
%{baseinstdir}/program/opengl/textFragmentShaderBatch.glsl
%{baseinstdir}/program/opengl/textVertexShader.glsl
%{baseinstdir}/program/opengl/textVertexShaderBatch.glsl
%{baseinstdir}/program/opengl/textureFragmentShader.glsl
%{baseinstdir}/program/opengl/textureVertexShader.glsl
%{baseinstdir}/program/opengl/transformedTextureVertexShader.glsl
%{baseinstdir}/program/types/offapi.rdb
%{baseinstdir}/program/libpasswordcontainerlo.so
%{baseinstdir}/program/pagein-common
%dir %{baseinstdir}/program/resource
%{baseinstdir}/program/resource/avmediaen-US.res
%{baseinstdir}/program/resource/accen-US.res
%{baseinstdir}/program/resource/basctlen-US.res
%{baseinstdir}/program/resource/biben-US.res
%{baseinstdir}/program/resource/chartcontrolleren-US.res
%{baseinstdir}/program/resource/cuien-US.res
%{baseinstdir}/program/resource/dbaen-US.res
%{baseinstdir}/program/resource/dbmmen-US.res
%{baseinstdir}/program/resource/dbuen-US.res
%{baseinstdir}/program/resource/dbwen-US.res
%{baseinstdir}/program/resource/deploymenten-US.res
%{baseinstdir}/program/resource/deploymentguien-US.res
%{baseinstdir}/program/resource/dkten-US.res
%{baseinstdir}/program/resource/editengen-US.res
%{baseinstdir}/program/resource/epsen-US.res
%{baseinstdir}/program/resource/euren-US.res
%{baseinstdir}/program/resource/fps_officeen-US.res
%{baseinstdir}/program/resource/frmen-US.res
%{baseinstdir}/program/resource/fween-US.res
%{baseinstdir}/program/resource/galen-US.res
%{baseinstdir}/program/resource/impen-US.res
%{baseinstdir}/program/resource/ofaen-US.res
%{baseinstdir}/program/resource/pcren-US.res
%{baseinstdir}/program/resource/pdffilteren-US.res
%{baseinstdir}/program/resource/sben-US.res
%{baseinstdir}/program/resource/scnen-US.res
%{baseinstdir}/program/resource/sden-US.res
%{baseinstdir}/program/resource/sfxen-US.res
%{baseinstdir}/program/resource/sdbten-US.res
%{baseinstdir}/program/resource/svlen-US.res
%{baseinstdir}/program/resource/svten-US.res
%{baseinstdir}/program/resource/svxen-US.res
%{baseinstdir}/program/resource/swen-US.res
%{baseinstdir}/program/resource/tplen-US.res
%{baseinstdir}/program/resource/uuien-US.res
%{baseinstdir}/program/resource/upden-US.res
%{baseinstdir}/program/resource/vclen-US.res
%{baseinstdir}/program/resource/writerperfecten-US.res
%{baseinstdir}/program/resource/wzien-US.res
%{baseinstdir}/program/resource/xmlsecen-US.res
%{baseinstdir}/program/resource/xsltdlgen-US.res
%{baseinstdir}/program/senddoc
%dir %{baseinstdir}/program/services
%{baseinstdir}/program/services/services.rdb
%{baseinstdir}/program/libsimplecanvaslo.so
%{baseinstdir}/program/libslideshowlo.so
%{baseinstdir}/program/libsofficeapp.so
%{baseinstdir}/program/libstringresourcelo.so
%{baseinstdir}/program/libsysshlo.so
%{baseinstdir}/program/libucpcmis1lo.so
%{baseinstdir}/program/libucpexpand1lo.so
%{baseinstdir}/program/libucpextlo.so
%{baseinstdir}/program/libucpimagelo.so
%{baseinstdir}/program/libucptdoc1lo.so
%{baseinstdir}/program/lounorc
%{baseinstdir}/program/libupdatefeedlo.so
%{baseinstdir}/program/uri-encode
%{baseinstdir}/program/libvbaeventslo.so
%{baseinstdir}/program/libvclcanvaslo.so
%{baseinstdir}/program/versionrc
%{baseinstdir}/program/xid-fullscreen-on-all-monitors
%dir %{baseinstdir}/share
%dir %{baseinstdir}/share/Scripts
%{baseinstdir}/share/Scripts/java
%dir %{baseinstdir}/share/autotext
%dir %{_datadir}/autocorr
%{baseinstdir}/share/autocorr
%{baseinstdir}/share/autotext/en-US
%{baseinstdir}/share/basic
%dir %{baseinstdir}/share/config
%{baseinstdir}/share/config/images_breeze.zip
%{baseinstdir}/share/config/images_galaxy.zip
%{baseinstdir}/share/config/images_hicontrast.zip
%{baseinstdir}/share/config/images_oxygen.zip
%{baseinstdir}/share/config/images_sifr.zip
%{baseinstdir}/share/config/images_tango.zip
%dir %{baseinstdir}/share/config/soffice.cfg
%{baseinstdir}/share/config/soffice.cfg/modules
%{baseinstdir}/share/config/soffice.cfg/*/ui
%exclude %{baseinstdir}/share/config/soffice.cfg/modules/*/ui/res/*
%exclude %{baseinstdir}/share/config/soffice.cfg/*/ui/res/*
%{baseinstdir}/share/palette
%{baseinstdir}/share/config/webcast
%{baseinstdir}/share/config/wizard
%dir %{baseinstdir}/share/dtd
%{baseinstdir}/share/dtd/officedocument
%{baseinstdir}/share/gallery
%dir %{baseinstdir}/share/labels
%{baseinstdir}/share/labels/labels.xml
%dir %{baseinstdir}/share/psprint
%config %{baseinstdir}/share/psprint/psprint.conf
%{baseinstdir}/share/psprint/driver
%dir %{baseinstdir}/share/registry
%{baseinstdir}/share/registry/gnome.xcd
%{baseinstdir}/share/registry/lingucomponent.xcd
%{baseinstdir}/share/registry/main.xcd
%{baseinstdir}/share/registry/oo-ad-ldap.xcd.sample
%{baseinstdir}/share/registry/oo-ldap.xcd.sample
%{baseinstdir}/share/registry/Langpack-en-US.xcd
%dir %{baseinstdir}/share/registry/res
%{baseinstdir}/share/registry/res/fcfg_langpack_en-US.xcd
%dir %{baseinstdir}/share/template
%{baseinstdir}/share/template/en-US
%dir %{baseinstdir}/share/template/common
%{baseinstdir}/share/template/common/internal
%{baseinstdir}/share/template/common/layout
%{baseinstdir}/share/template/common/officorr
%{baseinstdir}/share/template/common/offimisc
%{baseinstdir}/share/template/common/personal
%{baseinstdir}/share/template/common/presnt
%{baseinstdir}/share/template/common/styles
%{baseinstdir}/share/template/common/wizard
%{baseinstdir}/share/template/wizard
%dir %{baseinstdir}/share/wordbook
%{baseinstdir}/share/wordbook/en-GB.dic
%{baseinstdir}/share/wordbook/en-US.dic
%{baseinstdir}/share/wordbook/technical.dic
%{baseinstdir}/program/liblnthlo.so
%{_bindir}/unopkg
%{_mandir}/man1/unopkg.1*
%{baseinstdir}/program/libxmlsecurity.so
%{baseinstdir}/program/libconfigmgrlo.so
%{baseinstdir}/program/libdesktopbe1lo.so
%{baseinstdir}/program/libfsstoragelo.so
%{baseinstdir}/program/libi18npoollo.so
%{baseinstdir}/program/libbasegfxlo.so
# TODO: shouldn't it have lo suffix?
%{baseinstdir}/program/libcomphelper.so
%{baseinstdir}/program/libfwelo.so
%{baseinstdir}/program/libfwilo.so
%{baseinstdir}/program/libfwklo.so
%{baseinstdir}/program/libfwllo.so
%{baseinstdir}/program/libfwmlo.so
%{baseinstdir}/program/libi18nlangtag.so
# TODO: shouldn't it have lo suffix?
%{baseinstdir}/program/libi18nutil.so
%{baseinstdir}/program/libpackage2.so
%{baseinstdir}/program/libsblo.so
%{baseinstdir}/program/libsfxlo.so
%{baseinstdir}/program/libsotlo.so
%{baseinstdir}/program/libspllo.so
%{baseinstdir}/program/libsvllo.so
%{baseinstdir}/program/libsvtlo.so
%{baseinstdir}/program/libtklo.so
%{baseinstdir}/program/libtllo.so
%{baseinstdir}/program/libucb1.so
%{baseinstdir}/program/libucpfile1.so
%{baseinstdir}/program/libutllo.so
%{baseinstdir}/program/libvcllo.so
%{baseinstdir}/program/libwriterperfectlo.so
%{baseinstdir}/program/libxmlscriptlo.so
%{baseinstdir}/program/libxolo.so
%{baseinstdir}/program/liblocalebe1lo.so
%{baseinstdir}/program/libucpgio1lo.so
%{baseinstdir}/program/types/oovbaapi.rdb
#share unopkg
%dir %{baseinstdir}/share/extensions
%{baseinstdir}/share/extensions/package.txt
%{baseinstdir}/program/unopkg
%{baseinstdir}/program/unopkg.bin
%{baseinstdir}/program/bootstraprc
%{baseinstdir}/program/fundamentalrc
%{baseinstdir}/program/setuprc
%{baseinstdir}/program/intro.*
%{baseinstdir}/program/soffice
%{baseinstdir}/program/soffice.bin
%{baseinstdir}/program/sofficerc
%{baseinstdir}/program/unoinfo
%{baseinstdir}/program/oosplash
%{baseinstdir}/program/shell/
%dir %{baseinstdir}/share/filter
%{baseinstdir}/share/filter/oox-drawingml-adj-names
%{baseinstdir}/share/filter/oox-drawingml-cs-presets
%{baseinstdir}/share/filter/vml-shape-types
%{baseinstdir}/share/xdg/
%{baseinstdir}/program/redirectrc
%{_datadir}/applications/libreoffice-startcenter.desktop
#launchers
%{_bindir}/libreoffice
%{_bindir}/openoffice.org
%{_bindir}/soffice
%{_bindir}/ooffice
%{_bindir}/ooviewdoc
%{_mandir}/man1/libreoffice.1*
%{_mandir}/man1/openoffice.org.1*
%{_mandir}/man1/soffice.1*
%{_mandir}/man1/ooffice.1*
%{_mandir}/man1/ooviewdoc.1*

%if ! 0%{?file_triggers}
%post core
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun core
update-desktop-database %{_datadir}/applications &> /dev/null || :
%endif

%files base
%{baseinstdir}/help/en-US/sdatabase.*
%{baseinstdir}/program/classes/hsqldb.jar
%{baseinstdir}/program/classes/reportbuilder.jar
%{baseinstdir}/program/classes/reportbuilderwizard.jar
%{baseinstdir}/program/classes/sdbc_hsqldb.jar
%{baseinstdir}/program/libabplo.so
%{baseinstdir}/program/libdbplo.so
%{baseinstdir}/program/libhsqldb.so
%{baseinstdir}/program/librptlo.so
%{baseinstdir}/program/librptuilo.so
%{baseinstdir}/program/librptxmllo.so
%{baseinstdir}/program/resource/abpen-US.res
%{baseinstdir}/program/resource/cnren-US.res
%{baseinstdir}/program/resource/dbpen-US.res
%{baseinstdir}/program/resource/rpten-US.res
%{baseinstdir}/program/resource/rptuien-US.res
%{baseinstdir}/program/resource/sdbclen-US.res
%{baseinstdir}/program/resource/sdberren-US.res
%{baseinstdir}/share/registry/base.xcd
%{baseinstdir}/share/registry/reportbuilder.xcd
%{baseinstdir}/program/sbase
%{_datadir}/appdata/libreoffice-base.appdata.xml
%{_datadir}/applications/libreoffice-base.desktop
%{_bindir}/oobase
%{_mandir}/man1/oobase.1*

%if ! 0%{?file_triggers}
%post base
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun base
update-desktop-database %{_datadir}/applications &> /dev/null || :
%endif

%files bsh
%{baseinstdir}/program/classes/ScriptProviderForBeanShell.jar
%{baseinstdir}/program/services/scriptproviderforbeanshell.rdb
%{baseinstdir}/share/Scripts/beanshell

%files rhino
%{baseinstdir}/program/classes/js.jar
%{baseinstdir}/program/classes/ScriptProviderForJavaScript.jar
%{baseinstdir}/program/services/scriptproviderforjavascript.rdb
%{baseinstdir}/share/Scripts/javascript

%files wiki-publisher
%docdir %{baseinstdir}/share/extensions/wiki-publisher/license
%{baseinstdir}/share/extensions/wiki-publisher

%files nlpsolver
%docdir %{baseinstdir}/share/extensions/nlpsolver/help
%{baseinstdir}/share/extensions/nlpsolver

%files officebean
%{baseinstdir}/program/classes/officebean.jar
%{baseinstdir}/program/libofficebean.so

%files ogltrans
%{baseinstdir}/program/libOGLTranslo.so
%{baseinstdir}/program/opengl/basicFragmentShader.glsl
%{baseinstdir}/program/opengl/basicVertexShader.glsl
%{baseinstdir}/program/opengl/dissolveFragmentShader.glsl
%{baseinstdir}/program/opengl/fadeBlackFragmentShader.glsl
%{baseinstdir}/program/opengl/fadeFragmentShader.glsl
%{baseinstdir}/program/opengl/glitterFragmentShader.glsl
%{baseinstdir}/program/opengl/glitterVertexShader.glsl
%{baseinstdir}/program/opengl/honeycombFragmentShader.glsl
%{baseinstdir}/program/opengl/honeycombGeometryShader.glsl
%{baseinstdir}/program/opengl/honeycombVertexShader.glsl
%{baseinstdir}/program/opengl/rippleFragmentShader.glsl
%{baseinstdir}/program/opengl/reflectionFragmentShader.glsl
%{baseinstdir}/program/opengl/reflectionVertexShader.glsl
%{baseinstdir}/program/opengl/staticFragmentShader.glsl
%{baseinstdir}/program/opengl/vortexFragmentShader.glsl
%{baseinstdir}/program/opengl/vortexGeometryShader.glsl
%{baseinstdir}/program/opengl/vortexVertexShader.glsl
%{baseinstdir}/share/config/soffice.cfg/simpress/transitions-ogl.xml
%{baseinstdir}/share/registry/ogltrans.xcd

%files pdfimport
%{baseinstdir}/program/libpdfimportlo.so
%{baseinstdir}/program/xpdfimport
%{baseinstdir}/share/registry/pdfimport.xcd
%dir %{baseinstdir}/share/xpdfimport
%{baseinstdir}/share/xpdfimport/xpdfimport_err.pdf

%_font_pkg -n %{fontname} opens___.ttf
%doc instdir/LICENSE

%files calc
%{baseinstdir}/help/en-US/scalc.*
%{baseinstdir}/program/libanalysislo.so
%{baseinstdir}/program/libcalclo.so
%{baseinstdir}/program/libdatelo.so
%{baseinstdir}/program/libforlo.so
%{baseinstdir}/program/libforuilo.so

%{baseinstdir}/program/libpricinglo.so
%{baseinstdir}/program/libsclo.so
%{baseinstdir}/program/libscdlo.so
%{baseinstdir}/program/libscfiltlo.so
%{baseinstdir}/program/libscuilo.so
%{baseinstdir}/program/libsolverlo.so
%{baseinstdir}/program/libwpftcalclo.so
%{baseinstdir}/program/resource/analysisen-US.res
%{baseinstdir}/program/resource/dateen-US.res
%{baseinstdir}/program/resource/foren-US.res
%{baseinstdir}/program/resource/foruien-US.res
%{baseinstdir}/program/resource/pricingen-US.res
%{baseinstdir}/program/resource/scen-US.res
%{baseinstdir}/program/resource/solveren-US.res
%{baseinstdir}/program/libvbaobjlo.so
%{baseinstdir}/share/registry/calc.xcd
%{baseinstdir}/program/pagein-calc
%{baseinstdir}/program/scalc
%{_datadir}/appdata/libreoffice-calc.appdata.xml
%{_datadir}/applications/libreoffice-calc.desktop
%{_bindir}/oocalc
%{_mandir}/man1/oocalc.1*

%if ! 0%{?file_triggers}
%post calc
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun calc
update-desktop-database %{_datadir}/applications &> /dev/null || :
%endif

%files draw
%{baseinstdir}/help/en-US/sdraw.*
%{baseinstdir}/share/registry/draw.xcd
%{baseinstdir}/program/pagein-draw
%{baseinstdir}/program/sdraw
%{_datadir}/appdata/libreoffice-draw.appdata.xml
%{_datadir}/applications/libreoffice-draw.desktop
%{_bindir}/oodraw
%{_mandir}/man1/oodraw.1*

%if ! 0%{?file_triggers}
%post draw
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun draw
update-desktop-database %{_datadir}/applications &> /dev/null || :
%endif

%files emailmerge
%{baseinstdir}/program/mailmerge.py*
%{baseinstdir}/program/msgbox.py*

%files writer
%{baseinstdir}/help/en-US/swriter.*
%{baseinstdir}/program/libhwplo.so
%{baseinstdir}/program/liblwpftlo.so
%{baseinstdir}/program/libmswordlo.so
%{baseinstdir}/program/libswuilo.so
%{baseinstdir}/program/libt602filterlo.so
%{baseinstdir}/program/libwpftwriterlo.so
%{baseinstdir}/program/libwriterfilterlo.so
%{baseinstdir}/program/libvbaswobjlo.so
%{baseinstdir}/program/resource/t602filteren-US.res
%{baseinstdir}/share/registry/writer.xcd
%{baseinstdir}/program/pagein-writer
%{baseinstdir}/program/swriter
%{_datadir}/appdata/libreoffice-writer.appdata.xml
%{_datadir}/applications/libreoffice-writer.desktop
%{_bindir}/oowriter
%{_mandir}/man1/oowriter.1*

%if ! 0%{?file_triggers}
%post writer
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun writer
update-desktop-database %{_datadir}/applications &> /dev/null || :
%endif

%files impress
%{baseinstdir}/help/en-US/simpress.*
%{baseinstdir}/program/libanimcorelo.so
%{baseinstdir}/program/libplacewarelo.so
%{baseinstdir}/program/libPresentationMinimizerlo.so
%{baseinstdir}/program/libPresenterScreenlo.so
%{baseinstdir}/program/libwpftimpresslo.so
%dir %{baseinstdir}/share/config/soffice.cfg/simpress
%{baseinstdir}/share/config/soffice.cfg/simpress/effects.xml
%{baseinstdir}/share/config/soffice.cfg/simpress/layoutlist.xml
%{baseinstdir}/share/config/soffice.cfg/simpress/objectlist.xml
%{baseinstdir}/share/config/soffice.cfg/simpress/transitions.xml
%{baseinstdir}/share/registry/impress.xcd
%{baseinstdir}/program/pagein-impress
%{baseinstdir}/program/simpress
%{_datadir}/appdata/libreoffice-impress.appdata.xml
%{_datadir}/applications/libreoffice-impress.desktop
%{_bindir}/ooimpress
%{_mandir}/man1/ooimpress.1*

%if ! 0%{?file_triggers}
%post impress
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun impress
update-desktop-database %{_datadir}/applications &> /dev/null || :
%endif

%files math
%{baseinstdir}/help/en-US/smath.*
%{baseinstdir}/program/libsmlo.so
%{baseinstdir}/program/libsmdlo.so
%{baseinstdir}/program/resource/smen-US.res
%{baseinstdir}/share/registry/math.xcd
%{baseinstdir}/program/smath
%{_datadir}/applications/libreoffice-math.desktop
%{_bindir}/oomath
%{_mandir}/man1/oomath.1*

%if ! 0%{?file_triggers}
%post math
update-desktop-database %{_datadir}/applications &> /dev/null || :

%postun math
update-desktop-database %{_datadir}/applications &> /dev/null || :
%endif

%files graphicfilter
%{baseinstdir}/program/libflashlo.so
%{baseinstdir}/program/libgraphicfilterlo.so
%{baseinstdir}/program/libsvgfilterlo.so
%{baseinstdir}/program/libwpftdrawlo.so
%{baseinstdir}/share/registry/graphicfilter.xcd

%files xsltfilter
%{baseinstdir}/share/xslt
%{baseinstdir}/share/registry/xsltfilter.xcd
%{_datadir}/applications/libreoffice-xsltfilter.desktop

%files postgresql
%{baseinstdir}/program/libpostgresql-sdbclo.so
%{baseinstdir}/program/libpostgresql-sdbc-impllo.so
%{baseinstdir}/program/postgresql-sdbc.ini
%{baseinstdir}/program/services/postgresql-sdbc.rdb
%{baseinstdir}/share/registry/postgresql.xcd

%files ure
%{baseinstdir}/program/classes/java_uno.jar
%{baseinstdir}/program/classes/juh.jar
%{baseinstdir}/program/classes/jurt.jar
%{baseinstdir}/program/classes/ridl.jar
%{baseinstdir}/program/classes/unoloader.jar
%{baseinstdir}/program/javaldx
%{baseinstdir}/program/javavendors.xml
%{baseinstdir}/program/jvmfwk3rc
%{baseinstdir}/program/JREProperties.class
%{baseinstdir}/program/libaffine_uno_uno.so
%{baseinstdir}/program/libbinaryurplo.so
%{baseinstdir}/program/libbootstraplo.so
%{baseinstdir}/program/libgcc3_uno.so
%{baseinstdir}/program/libintrospectionlo.so
%{baseinstdir}/program/libinvocadaptlo.so
%{baseinstdir}/program/libinvocationlo.so
%{baseinstdir}/program/libiolo.so
%{baseinstdir}/program/libjava_uno.so
%{baseinstdir}/program/libjavaloaderlo.so
%{baseinstdir}/program/libjavavmlo.so
%{baseinstdir}/program/libjpipe.so
%{baseinstdir}/program/libjuh.so
%{baseinstdir}/program/libjuhx.so
%{baseinstdir}/program/libjvmaccesslo.so
%{baseinstdir}/program/libjvmfwklo.so
%{baseinstdir}/program/liblog_uno_uno.so
%{baseinstdir}/program/libnamingservicelo.so
%{baseinstdir}/program/libproxyfaclo.so
%{baseinstdir}/program/libreflectionlo.so
%{baseinstdir}/program/libreglo.so
%{baseinstdir}/program/libsal_textenclo.so
%{baseinstdir}/program/libstocserviceslo.so
%{baseinstdir}/program/libstorelo.so
%{baseinstdir}/program/libuno_cppu.so.3
%{baseinstdir}/program/libuno_cppuhelpergcc3.so.3
%{baseinstdir}/program/libuno_purpenvhelpergcc3.so.3
%{baseinstdir}/program/libuno_sal.so.3
%{baseinstdir}/program/libuno_salhelpergcc3.so.3
%{baseinstdir}/program/libunoidllo.so
%{baseinstdir}/program/libunsafe_uno_uno.so
%{baseinstdir}/program/libuuresolverlo.so
%{baseinstdir}/program/libxmlreaderlo.so
%{baseinstdir}/program/regmerge
%{baseinstdir}/program/regview
%{baseinstdir}/program/services.rdb
%{baseinstdir}/program/types.rdb
%{baseinstdir}/program/uno
%{baseinstdir}/program/uno.bin
%{baseinstdir}/program/unorc

%files sdk
%{sdkinstdir}/
%exclude %{sdkinstdir}/docs/
%exclude %{sdkinstdir}/examples/

%files sdk-doc
%docdir %{sdkinstdir}/docs
%{sdkinstdir}/docs/
%{sdkinstdir}/examples/

%files pyuno
%{baseinstdir}/program/libpyuno.so
%{baseinstdir}/program/pythonloader.py*
%{baseinstdir}/program/libpythonloaderlo.so
%{baseinstdir}/program/pythonloader.unorc
%{baseinstdir}/program/pythonscript.py*
%{baseinstdir}/program/pyuno.so
%{baseinstdir}/program/services/pyuno.rdb
%{baseinstdir}/program/services/scriptproviderforpython.rdb
%{baseinstdir}/program/wizards
%{baseinstdir}/share/Scripts/python
%exclude %{baseinstdir}/share/Scripts/python/LibreLogo
%{libo_python_sitearch}/uno.py*
%{libo_python_sitearch}/unohelper.py*
%{libo_python_sitearch}/officehelper.py*
%if 0%{libo_use_python3}
%{libo_python_sitearch}/__pycache__/uno.cpython-*
%{libo_python_sitearch}/__pycache__/unohelper.cpython-*
%{libo_python_sitearch}/__pycache__/officehelper.cpython-*
%endif
%{baseinstdir}/share/registry/pyuno.xcd

%files librelogo
%{baseinstdir}/share/registry/librelogo.xcd
%{baseinstdir}/share/Scripts/python/LibreLogo

%files glade
%{baseinstdir}/program/ui-previewer
%{_datadir}/glade
%{_datadir}/glade3

%files data
%{_datadir}/icons/hicolor/*/*/libreoffice*
%{_datadir}/icons/locolor/*/*/libreoffice*
%{_datadir}/mime-info/libreoffice.*
%{_datadir}/mime/packages/libreoffice.xml
%dir %{datadir}
%doc instdir/CREDITS.fodt
%doc instdir/LICENSE.html
%doc instdir/LICENSE.fodt
%doc instdir/LICENSE
%doc instdir/NOTICE
%license instdir/LICENSE

%post data
%if ! 0%{?file_triggers}
touch --no-create %{_datadir}/mime/packages &> /dev/null || :
%endif
for theme in hicolor locolor; do
    touch --no-create %{_datadir}/icons/$theme &>/dev/null || :
done

%postun data
if [ $1 -eq 0 ] ; then
%if ! 0%{?file_triggers}
    touch --no-create %{_datadir}/mime/packages &> /dev/null || :
    update-mime-database %{?fedora:-n} %{_datadir}/mime &> /dev/null || :
%endif
    for theme in hicolor locolor; do
        touch --no-create %{_datadir}/icons/$theme &>/dev/null || :
        gtk-update-icon-cache -q %{_datadir}/icons/$theme &>/dev/null || :
    done
fi

%posttrans data
%if ! 0%{?file_triggers}
update-mime-database %{?fedora:-n} %{_datadir}/mime &> /dev/null || :
%endif
for theme in hicolor locolor; do
    gtk-update-icon-cache -q %{_datadir}/icons/$theme &>/dev/null || :
done

%files x11
%{baseinstdir}/program/libvclplug_genlo.so

%files gtk2
%{baseinstdir}/program/libvclplug_gtklo.so

%if 0%{?fedora}

%files kde4
%{baseinstdir}/program/libkde4be1lo.so
%{baseinstdir}/program/libvclplug_kde4lo.so

%files gtk3
%{baseinstdir}/program/libvclplug_gtk3lo.so

%files -n libreofficekit
%{baseinstdir}/share/libreofficekit
%{_libdir}/girepository-1.0/LOKDocView-%{girapiversion}.typelib
%{_libdir}/liblibreofficekitgtk.so

%files -n libreofficekit-devel
%{_libdir}/gir-1.0/LOKDocView-%{girapiversion}.gir

%endif

%changelog
* Fri Aug 12 2016 Hugo De Zela <hugodz@winet.com.pe>
- Version 5.2.0
- Based on libreoffice-5.2.0.4-1.el7.centos.src
